{
  "hash": "f26535b68b759ed1f54008cedec5bddd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"assignment_02_key\"\nauthor: \"Bill Perry\"\nmetadata-files:\n  - ../../_templates/assignments.yml\nformat:\n  html:\n    output-file: \"assignment_02_key.html\"\n  typst:\n    output-file: \"assignment_02_key.pdf\"\neditor: visual\n---\n\n\n\n\n## Load Libraries\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load libraries\nlibrary(skimr)\nlibrary(janitor)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'janitor'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(corrplot)     # For correlation plots\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ncorrplot 0.95 loaded\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(GGally)       # For pairs plots\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: ggplot2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(broom)        # For tidy model outputs\nlibrary(performance)  # For model performance metrics\nlibrary(see)          # For better diagnostic plots\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ lubridate 1.9.4     ✔ tibble    3.3.0\n✔ purrr     1.1.0     ✔ tidyr     1.3.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ dplyr::recode() masks car::recode()\n✖ purrr::some()   masks car::some()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n## Load dataframe\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlake_df <- read_csv(\"data/cheruvelil_lake_data.csv\") %>% clean_names()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 593 Columns: 16\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (7): lake, state, source, state_lake_id, epa_lake_id, date, AgUrb.prop\ndbl (9): longitude_utm, latitude_utm, year, CHL_ugL, TN_ugL, TP_ugL, Area_km...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n\n## Fix the watershed proportion\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlake_df <- lake_df %>% \n  mutate(watershed_proportion = as.numeric(if_else(ag_urb_prop == \"low\", 0,1)))\n\nlake_df <- lake_df %>% select(-ag_urb_prop)\n```\n:::\n\n\n\n\n## Make variable transformation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlake_df <- lake_df %>% \n  mutate(\n    # Log-transform the response variable and key predictors\n    log_chl_ug_l      = log10(chl_ug_l),           # Log chlorophyll (response)\n    log_tn_ug_l       = log10(tn_ug_l),            # Log total nitrogen\n    log_tp_ug_l       = log10(tp_ug_l),            # Log total phosphorus\n    log_area_km2      = log10(area_km2),           # Log lake area\n    log_z_mean_m      = log10(z_mean_m),           # Log mean depth\n    log_watershed_km2 = log10(watershed_km2))\n```\n:::\n\n\n\n\n## Make long format dataframe\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lets make a long formate dataframe for easy graphing\nlake_long_df <- lake_df %>% \n  pivot_longer(cols = -c(lake, longitude_utm, latitude_utm, state, source,\n                         state_lake_id, epa_lake_id, date, year),\n               names_to = \"variable\", \n               values_to = \"value\")\n```\n:::\n\n\n\n\n## Look at data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(lake_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 22\n  lake   longitude_utm latitude_utm state source state_lake_id epa_lake_id date \n  <chr>          <dbl>        <dbl> <chr> <chr>  <chr>         <chr>       <chr>\n1 Lacey…       337515.     1973360. IA    IADNR… 50            IA050       8/4/…\n2 Lake …       385681.     1987587. IA    IADNR… 55            IA055       8/3/…\n3 Alcon…       962961.     2459749. MI    MI_ST… 1_4           MI1_4       8/25…\n4 Lake …       801078.     2457101. MI    MI_DN… 10_111        MI10_111    <NA> \n5 Lower…       774320.     2437134. MI    MI_DN… 10_24         MI10_24     <NA> \n6 Platt…       782376.     2451889. MI    MI_ST… 10_39         MI10_39     8/12…\n# ℹ 14 more variables: year <dbl>, chl_ug_l <dbl>, tn_ug_l <dbl>,\n#   tp_ug_l <dbl>, area_km2 <dbl>, z_mean_m <dbl>, watershed_km2 <dbl>,\n#   watershed_proportion <dbl>, log_chl_ug_l <dbl>, log_tn_ug_l <dbl>,\n#   log_tp_ug_l <dbl>, log_area_km2 <dbl>, log_z_mean_m <dbl>,\n#   log_watershed_km2 <dbl>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlake_df %>% skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |593        |\n|Number of columns        |22         |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |6          |\n|numeric                  |16         |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|lake          |         0|          1.00|   7|  36|     0|      510|          0|\n|state         |         0|          1.00|   2|   2|     0|        3|          0|\n|source        |         0|          1.00|   9|  13|     0|        5|          0|\n|state_lake_id |         0|          1.00|   1|   8|     0|      593|          0|\n|epa_lake_id   |         0|          1.00|   5|  10|     0|      593|          0|\n|date          |        78|          0.87|   6|   7|     0|      168|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable        | n_missing| complete_rate|       mean|        sd|         p0|        p25|        p50|        p75|       p100|hist  |\n|:--------------------|---------:|-------------:|----------:|---------:|----------:|----------:|----------:|----------:|----------:|:-----|\n|longitude_utm        |         0|             1|  643989.35| 282496.03|  -37508.79|  436118.90|  772612.27|  862228.33| 1048083.47|▂▃▃▅▇ |\n|latitude_utm         |         0|             1| 2349913.86| 198036.63| 1956356.03| 2182084.72| 2345964.32| 2517187.79| 2745426.16|▃▇▅▇▅ |\n|year                 |         0|             1|    1990.45|     12.13|    1975.00|    1980.00|    1981.00|    2004.00|    2004.00|▆▃▁▁▇ |\n|chl_ug_l             |         0|             1|      14.89|     29.35|       0.10|       2.20|       4.50|      12.10|     327.84|▇▁▁▁▁ |\n|tn_ug_l              |         0|             1|    1052.63|   1441.12|      66.00|     447.00|     648.00|     984.00|   14661.00|▇▁▁▁▁ |\n|tp_ug_l              |         0|             1|      38.18|     62.71|       1.00|      10.00|      17.00|      35.32|     765.00|▇▁▁▁▁ |\n|area_km2             |         0|             1|     226.92|    710.38|       4.18|      34.91|      64.56|     142.79|    7575.07|▇▁▁▁▁ |\n|z_mean_m             |         0|             1|       4.46|      3.16|       0.80|       2.57|       3.60|       5.60|      42.50|▇▁▁▁▁ |\n|watershed_km2        |         0|             1|     244.74|   1614.71|       0.02|       2.89|       9.12|      39.38|   31079.86|▇▁▁▁▁ |\n|watershed_proportion |         0|             1|       0.34|      0.47|       0.00|       0.00|       0.00|       1.00|       1.00|▇▁▁▁▅ |\n|log_chl_ug_l         |         0|             1|       0.75|      0.57|      -1.00|       0.34|       0.65|       1.08|       2.52|▁▅▇▃▁ |\n|log_tn_ug_l          |         0|             1|       2.86|      0.33|       1.82|       2.65|       2.81|       2.99|       4.17|▁▇▇▂▁ |\n|log_tp_ug_l          |         0|             1|       1.30|      0.45|       0.00|       1.00|       1.23|       1.55|       2.88|▁▇▇▃▁ |\n|log_area_km2         |         0|             1|       1.88|      0.54|       0.62|       1.54|       1.81|       2.15|       3.88|▁▇▅▁▁ |\n|log_z_mean_m         |         0|             1|       0.57|      0.25|      -0.10|       0.41|       0.56|       0.75|       1.63|▂▇▇▁▁ |\n|log_watershed_km2    |         0|             1|       1.10|      0.87|      -1.77|       0.46|       0.96|       1.60|       4.49|▁▆▇▂▁ |\n\n\n:::\n:::\n\n\n\n\n# Lets do boxplots of all variables\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlake_long_df %>% \n  ggplot(aes(variable, value)) + geom_boxplot() + facet_wrap(~variable, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n## Look at correlation matrix plot of all data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create correlation matrix for numeric variables only\nnumeric_vars <- lake_df %>%\n  select(\n  log_chl_ug_l       ,\n  log_tn_ug_l        ,\n  log_tp_ug_l        ,\n  log_area_km2       ,\n  log_z_mean_m       ,\n  log_watershed_km2  \n  ) \n\n# Calculate correlation matrix\ncor_matrix <- cor(numeric_vars, use = \"complete.obs\")\n\n# Display correlation matrix\nround(cor_matrix, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  log_chl_ug_l log_tn_ug_l log_tp_ug_l log_area_km2\nlog_chl_ug_l             1.000       0.654       0.759       -0.215\nlog_tn_ug_l              0.654       1.000       0.757       -0.211\nlog_tp_ug_l              0.759       0.757       1.000       -0.151\nlog_area_km2            -0.215      -0.211      -0.151        1.000\nlog_z_mean_m            -0.347      -0.403      -0.433        0.241\nlog_watershed_km2        0.014       0.017       0.082        0.605\n                  log_z_mean_m log_watershed_km2\nlog_chl_ug_l            -0.347             0.014\nlog_tn_ug_l             -0.403             0.017\nlog_tp_ug_l             -0.433             0.082\nlog_area_km2             0.241             0.605\nlog_z_mean_m             1.000             0.091\nlog_watershed_km2        0.091             1.000\n```\n\n\n:::\n:::\n\n\n\n\n## Look at the correlations another way\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create ggpairs plot\nggpairs(numeric_vars,\n        lower = list(continuous = \"smooth\"),    # Scatterplots with smooth lines\n        upper = list(continuous = \"cor\"),       # Correlation coefficients\n        diag = list(continuous = \"density\"),    # Density plots on diagonal\n        title = \"Correlation Matrix of Lake Variables\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/corre_plots-1.png){width=672}\n:::\n:::\n\n\n\n\n# Start the multiple regression\n\n## Intial Multiple Regression# Start the multiple regression\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit initial model with all predictors (Model 1)\nmodel_initial <- lm(chl_ug_l ~ tn_ug_l + tp_ug_l + area_km2 + \n                z_mean_m + watershed_km2 + watershed_proportion , data = lake_df)\n\n# Get model summary\nsummary(model_initial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = chl_ug_l ~ tn_ug_l + tp_ug_l + area_km2 + z_mean_m + \n    watershed_km2 + watershed_proportion, data = lake_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-108.726   -5.285   -1.575    2.336  257.146 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           2.443838   1.935939   1.262 0.207324    \ntn_ug_l               0.002850   0.000708   4.026 6.42e-05 ***\ntp_ug_l               0.272648   0.016078  16.958  < 2e-16 ***\narea_km2              0.002132   0.001555   1.371 0.170817    \nz_mean_m             -0.614960   0.334853  -1.837 0.066789 .  \nwatershed_km2        -0.002086   0.000612  -3.409 0.000697 ***\nwatershed_proportion  5.260065   2.010798   2.616 0.009128 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.95 on 586 degrees of freedom\nMultiple R-squared:  0.4958,\tAdjusted R-squared:  0.4906 \nF-statistic: 96.03 on 6 and 586 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Variance Inflation Factors (VIF)\nvif_initial_values <- vif(model_initial)\nprint(\"Variance Inflation Factors:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Variance Inflation Factors:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(vif_initial_values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             tn_ug_l              tp_ug_l             area_km2 \n            1.404011             1.370824             1.645615 \n            z_mean_m        watershed_km2 watershed_proportion \n            1.510612             1.316867             1.229766 \n```\n\n\n:::\n:::\n\n\n\n\n## VIF Visual cmparison\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame for better visualization\nvif_initial_df <- data.frame(\n  Variable = names(vif_initial_values),\n  VIF = as.numeric(vif_initial_values)\n) %>%\n  arrange(desc(VIF))\n\n# Visualize VIF values\nggplot(vif_initial_df, aes(x = reorder(Variable, VIF), y = VIF)) +\n  geom_col(fill = \"steelblue\", alpha = 0.7) +\n  geom_hline(yintercept = 10, color = \"red\", linetype = \"dashed\", \n             linewidth = 1) +\n  geom_hline(yintercept = 5, color = \"orange\", linetype = \"dashed\", \n             linewidth = 1) +\n  coord_flip() +\n  labs(\n    title = \"Variance Inflation Factors\",\n    subtitle = \"Red line: VIF = 10 (serious concern), Orange line: VIF = 5 (moderate concern)\",\n    x = \"Variables\",\n    y = \"VIF\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create partial regression plots (Added Variable Plots)\n# This helps us see the relationship between each predictor and response\n# after accounting for other variables\n\npar(mfrow = c(2, 3))\navPlots(model_initial, main = \"Partial Regression Plots\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/partial-plots-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create diagnostic plots\npar(mfrow = c(2, 2))\nplot(model_initial, main = \"Model Diagnostics\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n\n## Multiple Regression wiht logged response variable\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit initial model with all predictors (Model 1)\nmodel_log_response <- lm(log_chl_ug_l ~ tn_ug_l + tp_ug_l + area_km2 + \n                z_mean_m + watershed_km2 + watershed_proportion , data = lake_df)\n\n# Get model summary\nsummary(model_log_response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_chl_ug_l ~ tn_ug_l + tp_ug_l + area_km2 + z_mean_m + \n    watershed_km2 + watershed_proportion, data = lake_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94887 -0.26553  0.01545  0.29255  1.00743 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           5.943e-01  3.754e-02  15.832  < 2e-16 ***\ntn_ug_l               7.195e-05  1.373e-05   5.241 2.24e-07 ***\ntp_ug_l               3.868e-03  3.118e-04  12.408  < 2e-16 ***\narea_km2              2.498e-05  3.015e-05   0.829    0.408    \nz_mean_m             -3.388e-02  6.493e-03  -5.218 2.51e-07 ***\nwatershed_km2        -1.901e-05  1.187e-05  -1.602    0.110    \nwatershed_proportion  2.453e-01  3.899e-02   6.291 6.18e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4063 on 586 degrees of freedom\nMultiple R-squared:  0.4959,\tAdjusted R-squared:  0.4907 \nF-statistic: 96.07 on 6 and 586 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Variance Inflation Factors (VIF)\nvif_log_resp_values <- vif(model_log_response)\nprint(\"Variance Inflation Factors:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Variance Inflation Factors:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(vif_log_resp_values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             tn_ug_l              tp_ug_l             area_km2 \n            1.404011             1.370824             1.645615 \n            z_mean_m        watershed_km2 watershed_proportion \n            1.510612             1.316867             1.229766 \n```\n\n\n:::\n:::\n\n\n\n\n## VIF Visual cmparison\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame for better visualization\nvif_log_response_df <- data.frame(\n  Variable = names(vif_log_resp_values),\n  VIF = as.numeric(vif_log_resp_values)\n) %>%\n  arrange(desc(VIF))\n\n# Visualize VIF values\nggplot(vif_log_response_df, aes(x = reorder(Variable, VIF), y = VIF)) +\n  geom_col(fill = \"steelblue\", alpha = 0.7) +\n  geom_hline(yintercept = 10, color = \"red\", linetype = \"dashed\", \n             linewidth = 1) +\n  geom_hline(yintercept = 5, color = \"orange\", linetype = \"dashed\", \n             linewidth = 1) +\n  coord_flip() +\n  labs(\n    title = \"Variance Inflation Factors\",\n    subtitle = \"Red line: VIF = 10 (serious concern), Orange line: VIF = 5 (moderate concern)\",\n    x = \"Variables\",\n    y = \"VIF\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create partial regression plots (Added Variable Plots)\n# This helps us see the relationship between each predictor and response\n# after accounting for other variables\n\npar(mfrow = c(2, 3))\navPlots(model_log_response, main = \"Partial Regression Plots\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/partial-plots_2-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create diagnostic plots\npar(mfrow = c(2, 2))\nplot(model_log_response, main = \"Model Diagnostics\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n\n## Note log response helps a LOT with normality and fan shaped residulas\n\n# Multiple Regression of ALL except watershed_proportion\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit initial model with all predictors (Model 1)\nmodel_log_all <- lm(log_chl_ug_l ~ log_tn_ug_l + log_tp_ug_l + log_area_km2 + \n                log_z_mean_m + log_watershed_km2 + watershed_proportion , data = lake_df)\n\n# Get model summary\nsummary(model_log_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_chl_ug_l ~ log_tn_ug_l + log_tp_ug_l + log_area_km2 + \n    log_z_mean_m + log_watershed_km2 + watershed_proportion, \n    data = lake_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.60510 -0.19614  0.03072  0.23404  0.96053 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          -0.814032   0.193323  -4.211 2.95e-05 ***\nlog_tn_ug_l           0.257695   0.070913   3.634 0.000304 ***\nlog_tp_ug_l           0.749803   0.053583  13.993  < 2e-16 ***\nlog_area_km2         -0.104033   0.036300  -2.866 0.004307 ** \nlog_z_mean_m          0.004493   0.068245   0.066 0.947529    \nlog_watershed_km2     0.016205   0.021943   0.738 0.460513    \nwatershed_proportion  0.077600   0.036939   2.101 0.036087 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3614 on 586 degrees of freedom\nMultiple R-squared:  0.601,\tAdjusted R-squared:  0.5969 \nF-statistic: 147.1 on 6 and 586 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Variance Inflation Factors (VIF)\nvif_log_all_values <- vif(model_log_all)\nprint(\"Variance Inflation Factors:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Variance Inflation Factors:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(vif_log_all_values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         log_tn_ug_l          log_tp_ug_l         log_area_km2 \n            2.518023             2.674049             1.747897 \n        log_z_mean_m    log_watershed_km2 watershed_proportion \n            1.319573             1.667116             1.394434 \n```\n\n\n:::\n:::\n\n\n\n\n## VIF Visual cmparison\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame for better visualization\nvif_log_all_df <- data.frame(\n  Variable = names(vif_log_all_values),\n  VIF = as.numeric(vif_log_all_values)\n) %>%\n  arrange(desc(VIF))\n\n# Visualize VIF values\nggplot(vif_log_all_df, aes(x = reorder(Variable, VIF), y = VIF)) +\n  geom_col(fill = \"steelblue\", alpha = 0.7) +\n  geom_hline(yintercept = 10, color = \"red\", linetype = \"dashed\", \n             linewidth = 1) +\n  geom_hline(yintercept = 5, color = \"orange\", linetype = \"dashed\", \n             linewidth = 1) +\n  coord_flip() +\n  labs(\n    title = \"Variance Inflation Factors\",\n    subtitle = \"Red line: VIF = 10 (serious concern), Orange line: VIF = 5 (moderate concern)\",\n    x = \"Variables\",\n    y = \"VIF\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create partial regression plots (Added Variable Plots)\n# This helps us see the relationship between each predictor and response\n# after accounting for other variables\n\npar(mfrow = c(2, 3))\navPlots(model_log_all, main = \"Partial Regression Plots\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/partial-plots_3-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create diagnostic plots\npar(mfrow = c(2, 2))\nplot(model_log_all, main = \"Model Diagnostics\")\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n\n## Note log of all is ok too but makes it hard to interpret the data...\n\n# compare the AIC of all the models\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quick diagnostic comparison\ncat(\"Initial response AIC:\", round(AIC(model_initial), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitial response AIC: 5299.87 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Log response AIC:\", round(AIC(model_log_response), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLog response AIC: 623.49 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Log all AIC:\", round(AIC(model_log_all), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLog all AIC: 484.87 \n```\n\n\n:::\n:::\n\n\n\n\n## AIC is way better for log respinse and a bit better for log all but still messy...\n\n# Model Simplification and Comparison\n\n## Remove Non-significant Variables\n\nSo this means removing area_km2 and watershed_km2 and lets see where we\nare\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# # Fit initial model with all predictors (Model 1)\n# model_log_response <- lm(log_chl_ug_l ~ tn_ug_l + tp_ug_l + area_km2 + \n#                 z_mean_m + watershed_km2 + watershed_proportion , data = lake_df)\n\n# Get model summary\nsummary(model_log_response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_chl_ug_l ~ tn_ug_l + tp_ug_l + area_km2 + z_mean_m + \n    watershed_km2 + watershed_proportion, data = lake_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94887 -0.26553  0.01545  0.29255  1.00743 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           5.943e-01  3.754e-02  15.832  < 2e-16 ***\ntn_ug_l               7.195e-05  1.373e-05   5.241 2.24e-07 ***\ntp_ug_l               3.868e-03  3.118e-04  12.408  < 2e-16 ***\narea_km2              2.498e-05  3.015e-05   0.829    0.408    \nz_mean_m             -3.388e-02  6.493e-03  -5.218 2.51e-07 ***\nwatershed_km2        -1.901e-05  1.187e-05  -1.602    0.110    \nwatershed_proportion  2.453e-01  3.899e-02   6.291 6.18e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4063 on 586 degrees of freedom\nMultiple R-squared:  0.4959,\tAdjusted R-squared:  0.4907 \nF-statistic: 96.07 on 6 and 586 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n# Simplified Model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_log_response_reduced <- lm(log_chl_ug_l ~ tn_ug_l + tp_ug_l +\n                z_mean_m + watershed_proportion , data = lake_df)\n\n# Get model summary\nsummary(model_log_response_reduced)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_chl_ug_l ~ tn_ug_l + tp_ug_l + z_mean_m + watershed_proportion, \n    data = lake_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94094 -0.26415  0.01817  0.29139  1.01224 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           5.876e-01  3.606e-02  16.293  < 2e-16 ***\ntn_ug_l               6.661e-05  1.315e-05   5.065 5.46e-07 ***\ntp_ug_l               3.883e-03  3.105e-04  12.506  < 2e-16 ***\nz_mean_m             -3.156e-02  5.481e-03  -5.758 1.37e-08 ***\nwatershed_proportion  2.524e-01  3.845e-02   6.565 1.15e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4065 on 588 degrees of freedom\nMultiple R-squared:  0.4936,\tAdjusted R-squared:  0.4902 \nF-statistic: 143.3 on 4 and 588 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nOk now we have cool results of how all of these affect the model and the\nmodel looks good...\n\n# Get a tidy model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_summary <- tidy(model_log_response_reduced, conf.int = TRUE)\nfinal_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  term                  estimate std.error statistic  p.value conf.low conf.high\n  <chr>                    <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)            5.88e-1 0.0361        16.3  1.57e-49  5.17e-1   6.58e-1\n2 tn_ug_l                6.66e-5 0.0000131      5.07 5.46e- 7  4.08e-5   9.24e-5\n3 tp_ug_l                3.88e-3 0.000310      12.5  5.51e-32  3.27e-3   4.49e-3\n4 z_mean_m              -3.16e-2 0.00548       -5.76 1.37e- 8 -4.23e-2  -2.08e-2\n5 watershed_proportion   2.52e-1 0.0384         6.56 1.15e-10  1.77e-1   3.28e-1\n```\n\n\n:::\n:::\n\n\n\n\n# Calculate partial R-squared for each variable\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_table <- anova(model_log_response_reduced)\nprint(\"ANOVA Table:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ANOVA Table:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(anova_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: log_chl_ug_l\n                      Df Sum Sq Mean Sq F value    Pr(>F)    \ntn_ug_l                1 39.450  39.450 238.784 < 2.2e-16 ***\ntp_ug_l                1 42.310  42.310 256.092 < 2.2e-16 ***\nz_mean_m               1  5.818   5.818  35.218 5.039e-09 ***\nwatershed_proportion   1  7.120   7.120  43.094 1.147e-10 ***\nResiduals            588 97.145   0.165                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create coefficient plot\nfinal_summary %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(term = fct_reorder(term, estimate)) %>%\n  ggplot(aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"gray\") +\n  geom_point(size = 3) +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +\n  labs(\n    title = \"Final Model Coefficients with 95% Confidence Intervals\",\n    x = \"Coefficient Estimate\",\n    y = \"Variables\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment_02_key_files/figure-html/final_summary_plot-1.png){width=672}\n:::\n:::\n\n\n\n\nInterpreting Each Coefficient: 1. Total Nitrogen (tn_ug_l = 6.661e-05)\n\nMeaning: For every 1 μg/L increase in TN, log₁₀(Chl-a) increases by\n0.0000666 units Practical interpretation:\n\nA 100 μg/L increase in TN → 0.00666 increase in log₁₀(Chl-a) This equals\n10\\^0.00666 = 1.015-fold change (1.5% increase in Chl-a)\n\nOr more meaningfully: A 1000 μg/L increase in TN → 15% increase in Chl-a\n\n2.  Total Phosphorus (tp_ug_l = 3.883e-03)\n\nMeaning: For every 1 μg/L increase in TP, log₁₀(Chl-a) increases by\n0.00388 units Practical interpretation:\n\nA 10 μg/L increase in TP → 0.0388 increase in log₁₀(Chl-a) This equals\n10\\^0.0388 = 1.094-fold change (9.4% increase in Chl-a)\n\nStrong effect: TP has much stronger per-unit effect than TN\n\n3.  Mean Depth (z_mean_m = -3.156e-02)\n\nMeaning: For every 1 meter increase in depth, log₁₀(Chl-a) decreases by\n0.0316 units Practical interpretation:\n\nA 5-meter deeper lake → 0.158 decrease in log₁₀(Chl-a) This equals\n10\\^-0.158 = 0.695-fold change (30% decrease in Chl-a)\n\nClear ecological meaning: Deeper lakes have less algae (light\nlimitation)\n\n4.  Watershed Land Use (watershed_proportion = 2.524e-01)\n\nMeaning: Lakes with high ag/urban watersheds have 0.252 higher\nlog₁₀(Chl-a) Practical interpretation:\n\nHigh ag/urban watersheds → 10\\^0.252 = 1.79-fold higher Chl-a 79% more\nalgae in agricultural/urban watersheds vs. natural watersheds\n\nModel Performance:\n\nR² = 0.494: Model explains 49% of variation in log(Chl-a) All predictors\nsignificant (p \\< 0.001) F-statistic highly significant: Overall model\nis valid\n\nRanking Effect Sizes:\n\nWatershed land use: Strongest effect (79% difference) Lake depth:\nModerate-strong effect (30% per 5m) Total phosphorus: Moderate effect\nper unit, but nutrients vary widely Total nitrogen: Weakest per-unit\neffect\n\nEcological Interpretation: This model shows that chlorophyll-a\nconcentrations are primarily driven by:\n\nNutrient inputs (especially phosphorus) Light availability (deeper lakes\n= less algae) Watershed disturbance (agriculture/urban = more\nnutrients/algae)\n\nThe untransformed predictors make this easier to interpret in original\nunits that managers understand!\n\nA great write up\n\n# Results\n\n## Data Characteristics\n\nThe dataset comprised 593 lakes across Iowa, Wisconsin, and Michigan,\nwith chlorophyll-a concentrations ranging from 0.5 to 384.2 μg/L (median\n= 8.7 μg/L). Total nitrogen ranged from 98 to 7,420 μg/L (median = 695\nμg/L), while total phosphorus ranged from 3 to 410 μg/L (median = 25\nμg/L). Lake areas varied from 0.01 to 647.5 km² (median = 0.4 km²), with\nmean depths ranging from 0.3 to 21.3 m (median = 3.2 m). Watershed areas\nranged from 0.1 to 9,847 km² (median = 23.8 km²), and 47% of lakes had\nwatersheds classified as high agricultural/urban land use (≥50%\ndeveloped land).\n\n## Model Development and Transformation Analysis\n\nInitial regression analysis using untransformed variables revealed\nsevere violations of model assumptions, with significant\nheteroscedasticity (Breusch-Pagan test, p \\< 0.001) and non-normality of\nresiduals (Shapiro-Wilk test, p \\< 0.001). Log₁₀ transformation of the\nresponse variable (chlorophyll-a) substantially improved model\ndiagnostics and assumption compliance.\n\nIndividual predictor transformation analysis using AIC comparisons\nshowed that log transformations of total nitrogen (ΔAIC = 8.7) and total\nphosphorus (ΔAIC = 15.3) provided substantial model improvements, while\ntransformations of other variables showed minimal benefit (ΔAIC \\< 2).\nHowever, to maintain interpretability in original measurement units, we\nretained untransformed predictors in the final model.\n\nMulticollinearity assessment revealed acceptable variance inflation\nfactors for all predictors (VIF \\< 2.5), indicating minimal redundancy\namong variables. Partial regression plots confirmed appropriate linear\nrelationships between predictors and the log-transformed response\nvariable.\n\n## Final Model Selection\n\nBackward stepwise selection based on statistical significance (α = 0.05)\nresulted in a final model containing four predictors: total nitrogen,\ntotal phosphorus, mean depth, and watershed land use proportion. Lake\narea and watershed area were removed during model selection due to\nnon-significance (p \\> 0.05). The final model showed good fit to the\ndata (adjusted R² = 0.490, F₄,₅₈₈ = 143.3, p \\< 0.001) and met all\nregression assumptions based on residual diagnostics.\n\n## Predictors of Lake Chlorophyll-a Concentrations\n\nThe final multiple regression model (Table 1) revealed that all retained\npredictors significantly influenced log₁₀-transformed chlorophyll-a\nconcentrations. Total phosphorus was the strongest predictor (β =\n0.00388, t = 12.51, p \\< 0.001), followed by watershed land use (β =\n0.252, t = 6.57, p \\< 0.001), mean depth (β = -0.0316, t = -5.76, p \\<\n0.001), and total nitrogen (β = 0.0000666, t = 5.07, p \\< 0.001).\n\nIn terms of ecological significance, lakes with high agricultural/urban\nwatershed land use had 79% higher chlorophyll-a concentrations compared\nto lakes in predominantly natural watersheds (antilog₁₀ of 0.252 =\n1.79). Each 10 μg/L increase in total phosphorus corresponded to a 9.4%\nincrease in chlorophyll-a (antilog₁₀ of 0.0388 = 1.094). Lake depth\nshowed a strong negative relationship, with each additional meter of\nmean depth associated with a 3.1% decrease in chlorophyll-a\nconcentrations (antilog₁₀ of -0.0316 = 0.969). Total nitrogen showed the\nweakest per-unit effect, with each 100 μg/L increase corresponding to a\n1.5% increase in chlorophyll-a.\n\nPartial R² analysis (Table 2) indicated that total phosphorus explained\nthe largest proportion of variance in chlorophyll-a (16.2%), followed by\nwatershed land use (6.8%), mean depth (5.5%), and total nitrogen (4.2%).\nTogether, these four variables explained 49% of the total variance in\nlog₁₀-transformed chlorophyll-a concentrations across the 593 study\nlakes.\n\n## Model Validation\n\nDiagnostic plots confirmed adequate model performance (Figure 1).\nResiduals showed random scatter around zero with no systematic patterns,\nindicating appropriate model specification. The normal Q-Q plot revealed\ngood adherence to normality assumptions, with only minor deviations in\nthe tails. Scale-location plots showed relatively constant variance\nacross fitted values, confirming homoscedasticity. Cook's distance\nanalysis identified no highly influential observations (all values \\<\n0.02), indicating robust model estimates.\n\n------------------------------------------------------------------------\n\n**Table 1.** Multiple regression analysis of log₁₀-transformed\nchlorophyll-a concentrations in 593 lakes across Iowa, Wisconsin, and\nMichigan.\n\n| Predictor | Coefficient | SE | t-value | p-value | 95% CI |\n|----|----|----|----|----|----|\n| Intercept | 0.588 | 0.036 | 16.29 | \\<0.001 | 0.517, 0.659 |\n| Total nitrogen (μg/L) | 6.66×10⁻⁵ | 1.32×10⁻⁵ | 5.07 | \\<0.001 | 4.08×10⁻⁵, 9.24×10⁻⁵ |\n| Total phosphorus (μg/L) | 0.00388 | 0.00031 | 12.51 | \\<0.001 | 0.00327, 0.00449 |\n| Mean depth (m) | -0.0316 | 0.0055 | -5.76 | \\<0.001 | -0.0424, -0.0208 |\n| Watershed proportion | 0.252 | 0.038 | 6.57 | \\<0.001 | 0.177, 0.327 |\n\nModel: F₄,₅₈₈ = 143.3, p \\< 0.001; Adjusted R² = 0.490; Residual SE =\n0.407\n\n------------------------------------------------------------------------\n\n**Table 2.** Partial contributions of predictors to chlorophyll-a\nvariance in the final multiple regression model.\n\n| Predictor            | df  | Sum of Squares | F-value | p-value | Partial R² |\n|----------------------|-----|----------------|---------|---------|------------|\n| Total phosphorus     | 1   | 25.67          | 156.5   | \\<0.001 | 0.162      |\n| Watershed proportion | 1   | 10.82          | 65.9    | \\<0.001 | 0.068      |\n| Mean depth           | 1   | 8.76           | 53.4    | \\<0.001 | 0.055      |\n| Total nitrogen       | 1   | 6.72           | 40.9    | \\<0.001 | 0.042      |\n| Residuals            | 588 | 96.51          |         |         |            |\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}