project:
  type: website
  output-dir: docs

website:
  favicon: favicon.png
  title: "Bill's Biostats Website"
  site-url: https://wlperry.github.io/umd_biostats/index.html
  navbar:
    left:
      - href: about.qmd
        text: About
      href: about.qmd
        text: Perry's Site
      - https://wlperry.github.io/index.html
    tools:
      - icon: github
        href: https://github.com/wlperry
  reader-mode: false
  page-navigation: false
  back-to-top-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false

editor: visual

