project:
  type: website
  output-dir: docsd

website:
  favicon: favicon.png
  title: "Ben's Website"
  site-url: https://test.ben-gerdesmann.dog
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd
      - gallery.qmd
      - blog.qmd
    tools:
      - icon: twitter
        href: https://bsky.app/profile/ben-the-dog.bsky.social
      - icon: github
        href: https://github.com/BENevolent_code
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "The only cookies I like are the ones you can eat."
    background: light
  description: "Some posts about Ben."
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Please note** - This is a test website associated with the Quarto website tutorial at https://dgerdesmann.de/posts/3_Quarto Website/index.html"
    type: warning
    position: below-navbar

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false

editor: visual

