---
title: "UMD Biostatistics"
subtitle: "Data Analysis and Statistics for Biological Sciences"
description: "Welcome to the course website for UMD Biostatistics. Here you'll find the syllabus, schedule, lecture materials, activities, and assignments."
format: 
  html:
    freeze: auto
    toc: false
    toc-depth: 3
about:
  template: marquee
  links:
    - icon: github
      href: https://github.com/wlperry
    - icon: envelope-heart-fill
      href: mailto:wlperry@d.umn.edu
page-layout: full
---

# Welcome to Ecological Statistics at UMD!

This course teaches the fundamentals of statistics and data analysis for biological sciences. Using R and the tidyverse, you'll learn how to analyze and visualize data effectively to answer scientific questions.

## Course Materials

Materials for this course are organized into lectures, in-class activities, and homework assignments. All materials are available through this website and may be on canvas website at school.

## Course Schedule

Below is a summary of the course schedule.

+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| ## **Week**                                                    | ## **Readings**                                                           | ## **PowerPoint lecture**                                                | ## **In Class Activity**                                           | ## **Homework**                                                |
|                                                                |                                                                           |                                                                          |                                                                    |                                                                |
| ##                                                             | ##                                                                        | ##                                                                       | ##                                                                 | ##                                                             |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 01 Introduction - Start with R                                 | [R4DataScience Intro](https://r4ds.hadley.nz/intro.html)                  | [Lecture 1 PowerPoint](lectures/lecture_01/01_01_lecture_powerpoint.qmd) | [Lecture 1 Activity](lectures/lecture_01/01_02_class_activity.qmd) | [Week 1 Homework](lectures/lecture_01/01_03_take_homework.qmd) |
|                                                                |                                                                           |                                                                          |                                                                    |                                                                |
|                                                                | [R4DataScience Visualizaiton](https://r4ds.hadley.nz/data-visualize.html) |                                                                          |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 02 Project Design and Graphing data - GGPLOT                   | [R4DataScience Tidy Data](https://r4ds.hadley.nz/data-tidy.html)          | [PowerPoint](lectures/lecture_02/02_01_lecture_powerpoint.qmd)           | [Activity](lectures/lecture_02/02_02_class_activity.qmd)           |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 03 Descriptive Stats and wrangling                             |                                                                           | [PowerPoint](lectures/lecture_03/03_01_lecture_powerpoint.qmd)           | [Activity](lectures/lecture_03/03_02_class_activity.qmd)           | [Week 2 Homework](lectures/lecture_03/03_03_homework.qmd)      |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 04 Probability and Inference I - z distriubtions               |                                                                           | [PowerPoint](lectures/lecture_04/04_01_lecture_powerpoint.qmd)           | [Activity](lectures/lecture_04/04_02_class_activity.qmd)           |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 05 Probability and Inference II - t distribution               |                                                                           | [PowerPoint](lectures/lecture_05/05_01_lecture_powerpoint.qmd)           | [Activity](lectures/lecture_05/05_02_class_activity.qmd)           | [Week 3 Homework](lectures/lecture_05/05_03_homework.qmd)      |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 06 T-Tests                                                     |                                                                           | [PowerPoint](lectures/lecture_06/06_01_lecture_powerpoint.qmd)           | [Activity](lectures/lecture_06/06_02_class_activity.qmd)           |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 07 Non Parametric TTests                                       |                                                                           | [PowerPoint](lectures/lecture_07/07_01_lecture_powerpoint.qmd)           | [Activity](lectures/lecture_07/07_02_class_activity.qmd)           | Week 5 Homework                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 08 Study Design for more than T-Tests - Sampling               |                                                                           | [PowerPoint](lectures/lecture_08/08_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 09 Correlation vs Linear Models - Regression I                 |                                                                           | [PowerPoint](lectures/lecture_09/09_01_lecture_powerpoint.qmd)           | Activity                                                           |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 10 Regressions II                                              |                                                                           | [PowerPoint](lectures/lecture_10/10_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 11 Multiple Regression                                         |                                                                           | [PowerPoint](lectures/lecture_11/11_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 12 Analysis of Variance                                        |                                                                           | [PowerPoint](lectures/lecture_12/12_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 13 Analysis of Variance - 2 way anova                          |                                                                           | [PowerPoint](lectures/lecture_13/13_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 14 Analysis of Variance - nested anovas                        |                                                                           | [PowerPoint](lectures/lecture_14/14_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 15 GLM and Logistic Regression (27) - What if assumptions Fail |                                                                           | [PowerPoint](lectures/lecture_15/15_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 16 ANCOVA - Analysis of Covariance (20)                        |                                                                           | [PowerPoint](lectures/lecture_16/16_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 17 Multivariate Statistics (21)                                |                                                                           | [PowerPoint](lectures/lecture_17/17_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 18 Principal Component Analysis - PCA (23)                     |                                                                           | [PowerPoint](lectures/lecture_18/18_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 19 NMDS - CLUSTER ANALYSIS - HYPOTHESES (25)                   |                                                                           | [PowerPoint](lectures/lecture_19/19_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+
| 20 - Review (28)                                               |                                                                           | [PowerPoint](lectures/lecture_20/20_01_lecture_powerpoint.qmd)           |                                                                    |                                                                |
+----------------------------------------------------------------+---------------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------------------+

-   Order of topics is subject to change depending on the progress of the class. Changes to the class schedule will be announced in class.

## Required Readings

-   [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickham
-   [Whitlock and Schluter The Analysis of Biological Data - 3rd edition](https://store.macmillanlearning.com/us/product/The-Analysis-of-Biological-Data/p/131922623X?srsltid=AfmBOoqRmMWAOsajlUfAZPt1_UGqjmpPzMg-XAgjFhp5oP3mFNKUCw-w)
-   

## Helpful Links for resources

I have put together a page of [helpful links](links.qmd) that might be of great help as you move through the class

## Course [Schedule and Syllabus](syllabus.qmd)

## I have put together a set of all [statistical tests we have done](test_overviews/stats_tests_index.qmd)

Below is a link to all the statistical tests that we are covering in the class. These should be helpful to accomplish most of the statistics you will need to do. The format of all of these tests is:

-   type of data for the test
-   hypotheses being tests
-   assumptions of the test
-   the test itself and interpretation of the output
-   tests of assumptions
-   how to make a final publication quality plot
-   how to write up the results of your output

## Questions or Issues?

If you have questions about the course or the website, please contact me at [wlperry\@d.umn.edu](mailto:wlperry@d.umn.edu)
