{
  "hash": "017bca6f191a9e51edc4b9533d4f0968",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 14 - Factorial ANOVA of Limpet Egg Production\"\nauthor: \"Bill Perry\"\nexecute:\n  freeze: auto\n  cache: true\n  echo: true\n  keep-md: true\n  message: false\n  warning: false\n  fig-height: 5\n  fig-width: 4\n  paged-print: false\nformat:\n  html:\n    toc: false\n    output-file: \"14_03_factorial_anova_html.html\"\n    embed-resources: true\n    self-contained: true\n    max-width: 80ch\n    css: ../../css/lecture.css\n  revealjs:\n    output-file: \"14_03_factorial_anova_slides.html\"\n    self-contained: true\n    css: ../../css/lecture.css\n    slide-number: true\n    transition: fade\n  docx:\n    default: true\n    toc: false\n    toc-depth: 3\n    number-sections: true\n    highlight-style: github\n    reference-doc: ../../ms_templates/custom-reference.docx\n    css: msword.css\n    embed-resources: true\n  pptx:\n    reference-doc: ../../ms_templates/lecture_template.pptx \n    embed-resources: true\neditor: visual\n---\n\n\n\n\n\n\n\n\n\n\n# Lecture 13: Review\n\n::::: columns\n::: {.column width=\"60%\"}\nMultifactor ANOVA\n\n-   Example\n-   Linear model\n-   Analysis of variance\n-   Null hypotheses\n-   Interactions and main effects\n-   Unequal sample size\n-   Assumptions\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-1642768928.png){width=\"391\"}\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n2-factor designs (2-way ANOVA)\n\n-   very common in ecology\n-   Can have more factors (e.g., 3-way ANOVA)\n-   interpretation gets challenging\n-   Most multifactor designs: nested or factorial\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-3287272591.png){width=\"240\"}\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nConsider two factors:\n\n-   A and B Nested/hierarchical:\n    -   levels of B occur only in 1 level of A\n-   Factorial/crossed:\n    -   every level of B in every level of A\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-2737690912.png){width=\"332\"}\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nIn factorial designs\n\n-   look at two types of factor effects:\n\n    -   Main effect of each factor (polling across other factor)\n\n    -   Interaction effects; is there synergistic/ antagonistic effect of factors?\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-1252866044.png){width=\"417\"}\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nEffect of season and density on limpet fecundity.\n\n-   2 seasons (factor A)\n-   4 density treatments (factor B)\n-   3 replicates in each cell\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-557582806.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nConsider a crossed design with:\n\n-   p levels of factor A (i= 1…p) (2 seasons)\n-   q levels of factor B (j= 1…q), crossed with each level of A (4 density levels)\n-   n~i~ replicates (k= 1…n~i~) in each combination of A and B (3 replicate plates per density per season)\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-711980050.png){width=\"126\"}\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\nWe can calculate several means:\n\n-   overall mean (across all levels of A and B)= µ\n\n![](images/clipboard-666661894.png)\n\n# Lecture 14: Factorial ANOVA\n\nWe can calculate several means:\n\n-   Marginal means for levels of each factor, pooling across all levels of other factor\\\n-   Marginal mean for levels of A= µi\n-   Marginal mean for levels of B= µj\n\n![](images/clipboard-666661894.png)\n\n# Lecture 14: Factorial ANOVA\n\nWe can calculate several means:\n\n-   a mean for each cell of combinations of A and B= µ~ij~\n\n![](images/clipboard-666661894.png)\n\n# Lecture 14: Factorial ANOVA\n\nFactorial designs can be of 3 types:\n\n-   2 fixed factors (model 1 ANOVA)\n-   2 random (model 2 ANOVA)\n-   1 fixed, 1 random (mixed model- model 3 ANOVA)\n\nModel 1 ANOVA:\n\n## $$y_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\varepsilon_{ijk}$$\n\n## $$y_{ijk} = \\mu + \\alpha_i + \\beta_{j(i)} + \\varepsilon_{ijk}$$\n\n## Lecture 14: Factorial ANOVA\n\n## $$y_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\varepsilon_{ijk}$$\n\n-   $y_{ijk}$: value of the k~th~ observation from jth and ith combination of B and A (fecundity on 2nd plate, in “8 per plate” density in summer)\n-   µ: overall mean (overall fecundity)\n-   αi: effect of the ith level of A, pooling across all levels of B: µi- µ (difference between average fecundity in all “8 per plate” treatments and overall mean)\n\n# Lecture 14: Factorial ANOVA\n\n## $$y_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\varepsilon_{ijk}$$\n\n-   Βj: effect of jth level of B, pooling across all levels of A: µj- µ (difference between average fecundity in all winter treatments and overall mean)\n-   (αβ)ij: effect of interaction of ith level of A and jth level of B (µij - µi - µj + µ).\n    -   Does effect of B depend on level of A? (is effect of density different in winter and summer?)\n\n# Lecture 14: Factorial ANOVA\n\n## $$y_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\varepsilon_{ijk}$$\n\n-   Model 2 ANOVA rare in ecology\n-   Model 3 interpretation is different:\n    -   βj: random variable measuring variance in y across all possible levels of B, pooling across all levels of A\n    -   (αβ)ij is random variable measuring variance of interaction bw A and B across all possible levels of B (“is effect of A consistent across all possible levels of B that could have been chosen?”)\n\n# Lecture 14: Factorial ANOVA\n\nSSA is SS of differences between each marginal mean of A and overall mean\n\n| Source | SS | df | MS |\n|:-----------------|:-----------------|:-----------------|:-----------------|\n| A | $nq \\sum_{i=1}^{p} (\\bar{y}_{i.} - \\bar{y})^2$ | $p-1$ | $\\frac{SS_A}{p-1}$ |\n| B | $np \\sum_{j=1}^{q} (\\bar{y}_{.j} - \\bar{y})^2$ | $q-1$ | $\\frac{SS_B}{q-1}$ |\n| AB | $n \\sum_{i=1}^{p} \\sum_{j=1}^{q} (\\bar{y}_{ij} - \\bar{y}_{i.} - \\bar{y}_{.j} + \\bar{y})^2$ | $(p-1)(q-1)$ | $\\frac{SS_{AB}}{(p-1)(q-1)}$ |\n| Residual | $\\sum_{i=1}^{p} \\sum_{j=1}^{q} \\sum_{k=1}^{n} (y_{ijk} - \\bar{y}_{ij})^2$ | $pq(n-1)$ | $\\frac{SS_{\\text{Residual}}}{pq(n-1)}$ |\n| Total | $\\sum_{i=1}^{p} \\sum_{j=1}^{q} \\sum_{k=1}^{n} (y_{ijk} - \\bar{y})^2$ | $pqn-1$ |  |\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSSA is SS of differences between each marginal mean of A and overall mean\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-3497318309.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSSB is SS of differences between each marginal mean of B and overall mean\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-4218970939.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSSB is SS of differences between each marginal mean of B and overall mean\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-1204116459.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSSAB is SS of cell means minus marginal means plus overall mean\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-3485990288.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSSAB is SS of cell means minus marginal means plus overall mean\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-131008782.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSSresid is difference between each observation and the appropriate cell mean, summed over all observations\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-3811347300.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSStotal = SSA + SSB + SSAB + SSresid\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-4131888930.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\nSS converted to MS;\n\n-   F-ratio calculations are different depending on whether factors are fixed, random or mixed\n\n| Source | A and B fixed | A and B random | A fixed, B random |\n|:--------|:--------------------:|:----------------:|:----------------:|\n| A | $\\frac{MS_A}{MS_{Residual}}$ | $\\frac{MS_A}{MS_{AB}}$ | $\\frac{MS_A}{MS_{AB}}$ |\n| B | $\\frac{MS_B}{MS_{Residual}}$ | $\\frac{MS_B}{MS_{AB}}$ | $\\frac{MS_B}{MS_{AB}}$ |\n| AB | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ |\n\n# Lecture 14: Factorial ANOVA\n\n3 hypotheses are tested in a two-way factorial ANOVA:\n\n-   A, B, A\\*B Both factors fixed:\n\n-   Ho(A): µ1= - - µ2= µ3=…. µi= µp (no diff. in marginal means of A, pooling across all levels of B)\n\n-   Ho(B): µ1= µ2= - µ3=…. µj= µq (no diff. in marginal means of B, pooling across all levels of A)\n\n-   Ho(AB): µij- µi - - µj + µ = 0 (no effect of interaction)\n\n# Lecture 14: Factorial ANOVA\n\n| Source | A and B fixed | A and B random | A fixed, B random |\n|:---------|:----------------:|:----------------:|:----------------:|\n| A | $\\frac{MS_A}{MS_{Residual}}$ | $\\frac{MS_A}{MS_{AB}}$ | $\\frac{MS_A}{MS_{AB}}$ |\n| B | $\\frac{MS_B}{MS_{Residual}}$ | $\\frac{MS_B}{MS_{AB}}$ | $\\frac{MS_B}{MS_{AB}}$ |\n| AB | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ |\n\n# Lecture 14: Factorial ANOVA\n\n3 hypotheses are tested in a two-way factorial ANOVA: A, B, A\\*B\n\nBoth factors random:\n\n-   Ho(A): σA2= 0 (no added variance due to levels of A that could have been used)\n-   Ho(B): σB2= 0 (no added variance due to levels of B that could have been used)\n-   Ho(AB): σAB2= 0 (no added variance due to interaction between all levels of A and B that could have been used)\n\nThe random effect hypothesis tests whether there is significant variation or \"added variance\" in the data that can be attributed to the random groups or individuals within the fixed groups. In other words, it examines whether there are factors beyond the fixed conditions that contribute to the variability in the data.\n\n# Lecture 14: Factorial ANOVA\n\n| Source | A and B fixed | A and B random | A fixed, B random |\n|:-----------------|:----------------:|:----------------:|:----------------:|\n| A | $\\frac{MS_A}{MS_{Residual}}$ | $\\frac{MS_A}{MS_{AB}}$ | $\\frac{MS_A}{MS_{AB}}$ |\n| B | $\\frac{MS_B}{MS_{Residual}}$ | $\\frac{MS_B}{MS_{AB}}$ | $\\frac{MS_B}{MS_{AB}}$ |\n| AB | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ |\n\n# Lecture 14: Factorial ANOVA\n\n3 hypotheses are tested in a two-way factorial ANOVA: A, B, A\\*B\n\n-   Both factors random:\n    -   Ho(A): σA2= 0 (no added variance due to levels of A that could have been used)\n    -   Ho(B): σB2= 0 (no added variance due to levels of B that could have been used)\n    -   Ho(AB): σAB2= 0 (no added variance due to interaction between all levels of A and B that could have been used)\n\n# Lecture 14: Factorial ANOVA\n\n3 hypotheses are tested in a two-way factorial ANOVA: A, B, A\\*B\n\n-   One fixed, one random:\n\n    -   Ho(A): µ1= µ2= µ3=…. µi= µp (no diff. in marginal means of A, pooling across all levels of B)\n\n    -   Ho(B): σB2= 0 (no added variance due to levels of B that could have been used)\n\n    -   Ho(AB): σAB2= 0 (no added variance due to interaction between all levels of A and B that could have been used)\n\n# Lecture 14: Factorial ANOVA\n\n| Source | A and B fixed | A and B random | A fixed, B random |\n|:-----------------|:----------------:|:----------------:|:----------------:|\n| A | $\\frac{MS_A}{MS_{Residual}}$ | $\\frac{MS_A}{MS_{AB}}$ | $\\frac{MS_A}{MS_{AB}}$ |\n| B | $\\frac{MS_B}{MS_{Residual}}$ | $\\frac{MS_B}{MS_{AB}}$ | $\\frac{MS_B}{MS_{AB}}$ |\n| AB | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ | $\\frac{MS_{AB}}{MS_{Residual}}$ |\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nSo lets try the example with the fecundity of limpets in low and high tide areas of a rocky inter-tidal area\n\nEffect of season and density on limpet fecundity.\n\n-   2 seasons (factor A)\n\n-   4 density treatments (factor B)\n\n-   3 replicates in each cell\n\n-   This is data from Quinn and Keough Edition 1 box 9.4\n\n-   This analysis examines the effects of season (winter/spring vs. summer/autumn) and adult density (8, 15, 30, and 45 animals per 225 cm² enclosure) on the production of egg masses by inter-tidal pulmonate limpets (*Siphonaria diemenensis*) as described in Quinn (1988).\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-557582806.png)\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nThe set up and data overview\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)\nlibrary(car)       # For Levene's test and Type III SS\nlibrary(emmeans)   # For estimated marginal means\nlibrary(broom)     # For tidying model outputs\nlibrary(patchwork) # For combining plots\n\n# Set theme for plots\ntheme_set(theme_bw(base_size = 12))\n\n# Read the data\nquinn_data <- read_csv(\"data/quinn.csv\")\n\n# Convert factors\nquinn_data <- quinn_data %>%\n  mutate(\n    DENSITY = factor(DENSITY, levels = c(8, 15, 30, 45)),\n    SEASON = factor(SEASON)\n  )\n\n# Summary statistics\nquinn_data %>%\n  group_by(DENSITY, SEASON) %>%\n  summarise(\n    mean_eggs = mean(EGGS),\n    sd_eggs = sd(EGGS),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n# Groups:   DENSITY [4]\n  DENSITY SEASON mean_eggs sd_eggs     n\n  <fct>   <fct>      <dbl>   <dbl> <int>\n1 8       spring     2.42    0.591     3\n2 8       summer     1.83    0.315     3\n3 15      spring     2.18    0.379     3\n4 15      summer     1.18    0.482     3\n5 30      spring     1.57    0.621     3\n6 30      summer     0.811   0.411     3\n7 45      spring     1.20    0.190     3\n8 45      summer     0.593   0.205     3\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n##  ANOVA Assumptions\n\nBefore conducting the factorial ANOVA, we need to check several assumptions:\n\n1.  Independence of observations\n2.  Normality of residuals\n3.  Homogeneity of variances\n\n### \n:::\n\n::: {.column width=\"40%\"}\nFit the model\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the factorial ANOVA using linear model (lm) instead of aov\nquinn_model_lm <- lm(EGGS ~ DENSITY * SEASON, data = quinn_data)\n\n# View the model summary to see coefficients, standard errors, etc.\nsummary(quinn_model_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = EGGS ~ DENSITY * SEASON, data = quinn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.6667 -0.2612 -0.0610  0.2292  0.6647 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             2.41667    0.24642   9.807  3.6e-08 ***\nDENSITY15              -0.23933    0.34849  -0.687  0.50206    \nDENSITY30              -0.85133    0.34849  -2.443  0.02655 *  \nDENSITY45              -1.21700    0.34849  -3.492  0.00301 ** \nSEASONsummer           -0.58333    0.34849  -1.674  0.11358    \nDENSITY15:SEASONsummer -0.41633    0.49284  -0.845  0.41069    \nDENSITY30:SEASONsummer -0.17067    0.49284  -0.346  0.73363    \nDENSITY45:SEASONsummer -0.02367    0.49284  -0.048  0.96229    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4268 on 16 degrees of freedom\nMultiple R-squared:  0.749,\tAdjusted R-squared:  0.6392 \nF-statistic: 6.822 on 7 and 16 DF,  p-value: 0.000745\n```\n\n\n:::\n\n```{.r .cell-code}\n# Store residuals for diagnostics\nquinn_data$residuals <- residuals(quinn_model_lm)\nquinn_data$fitted <- fitted(quinn_model_lm)\n\n# For backward compatibility with later code\nquinn_model <- aov(quinn_model_lm)\n\nsummary(quinn_model_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = EGGS ~ DENSITY * SEASON, data = quinn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.6667 -0.2612 -0.0610  0.2292  0.6647 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             2.41667    0.24642   9.807  3.6e-08 ***\nDENSITY15              -0.23933    0.34849  -0.687  0.50206    \nDENSITY30              -0.85133    0.34849  -2.443  0.02655 *  \nDENSITY45              -1.21700    0.34849  -3.492  0.00301 ** \nSEASONsummer           -0.58333    0.34849  -1.674  0.11358    \nDENSITY15:SEASONsummer -0.41633    0.49284  -0.845  0.41069    \nDENSITY30:SEASONsummer -0.17067    0.49284  -0.346  0.73363    \nDENSITY45:SEASONsummer -0.02367    0.49284  -0.048  0.96229    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4268 on 16 degrees of freedom\nMultiple R-squared:  0.749,\tAdjusted R-squared:  0.6392 \nF-statistic: 6.822 on 7 and 16 DF,  p-value: 0.000745\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Check for Normality of Residuals\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create Q-Q plot of residuals\nggplot(quinn_data, aes(sample = residuals)) +\n  stat_qq() +\n  stat_qq_line() +\n  labs(title = \"Q-Q Plot of Residuals\",\n       x = \"Theoretical Quantiles\",\n       y = \"Sample Quantiles\")\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/normality_1-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Check for Normality of Residuals\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of residuals\nggplot(quinn_data, aes(x = residuals)) +\n  geom_histogram(bins = 8, fill = \"steelblue\", color = \"black\") +\n  labs(title = \"Histogram of Residuals\",\n       x = \"Residuals\",\n       y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/normality_2-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Check for Normality of Residuals\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shapiro-Wilk test for normality\nshapiro.test(quinn_data$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  quinn_data$residuals\nW = 0.97373, p-value = 0.7587\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Check for homogeneity of variances\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Levene's test for homogeneity of variances\nleveneTest(EGGS ~ DENSITY * SEASON, data = quinn_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  7  0.3337 0.9268\n      16               \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Check for homogeneity of variances\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residuals vs. fitted values plot\nggplot(quinn_data, aes(x = fitted, y = residuals)) +\n  geom_point() +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(title = \"Residuals vs. Fitted Values\",\n       x = \"Fitted Values\",\n       y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/homogeneity_2-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Check for homogeneity of variances\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residuals by group\nggplot(quinn_data, aes(x = interaction(DENSITY, SEASON), y = residuals)) +\n  geom_boxplot() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  labs(title = \"Residuals by Treatment Combination\",\n       x = \"Density and Season\",\n       y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/homogeneity_3-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# \n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\nNow to run the Factorial ANOVA\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run ANOVA with Type III SS using Anova function from car package\nanova_results_lm <- Anova(quinn_model_lm, type = \"III\")\nprint(anova_results_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: EGGS\n                Sum Sq Df F value    Pr(>F)    \n(Intercept)    17.5208  1 96.1809 3.599e-08 ***\nDENSITY         2.7954  3  5.1152   0.01136 *  \nSEASON          0.5104  1  2.8019   0.11358    \nDENSITY:SEASON  0.1647  3  0.3014   0.82395    \nResiduals       2.9146 16                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Get traditional ANOVA table from linear model\nanova(quinn_model_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: EGGS\n               Df Sum Sq Mean Sq F value    Pr(>F)    \nDENSITY         3 5.2841  1.7614  9.6691 0.0007041 ***\nSEASON          1 3.2502  3.2502 17.8419 0.0006453 ***\nDENSITY:SEASON  3 0.1647  0.0549  0.3014 0.8239545    \nResiduals      16 2.9146  0.1822                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# # Get parameter estimates and tests for linear model coefficients\n# summary(quinn_model_lm)\n# \n# # Get confidence intervals for the coefficients\n# confint(quinn_model_lm)\n# \n# # Get standardized coefficients\n# car::vif(quinn_model_lm)\n```\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## To get the polynomial and quadratic contrasts\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Polynomial contrasts using linear models\n# Create a model with ordered factor and orthogonal polynomials\nquinn_data$DENSITY_ord <- factor(quinn_data$DENSITY, \n                                levels = c(8, 15, 30, 45),\n                                ordered = TRUE)\n\n# Set up polynomial contrasts\ncontrasts(quinn_data$DENSITY_ord) <- contr.poly(4)\n\n# Fit model with polynomial contrasts\nquinn_poly_lm <- lm(EGGS ~ DENSITY_ord * SEASON, data = quinn_data)\n\n# Show model summary to see polynomial coefficients\nsummary(quinn_poly_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = EGGS ~ DENSITY_ord * SEASON, data = quinn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.6667 -0.2612 -0.0610  0.2292  0.6647 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 1.83975    0.12321  14.932 8.18e-11 ***\nDENSITY_ord.L              -0.95324    0.24642  -3.868 0.001362 ** \nDENSITY_ord.Q              -0.06317    0.24642  -0.256 0.800955    \nDENSITY_ord.C               0.13841    0.24642   0.562 0.582105    \nSEASONsummer               -0.73600    0.17424  -4.224 0.000645 ***\nDENSITY_ord.L:SEASONsummer  0.03906    0.34849   0.112 0.912158    \nDENSITY_ord.Q:SEASONsummer  0.28167    0.34849   0.808 0.430798    \nDENSITY_ord.C:SEASONsummer -0.17009    0.34849  -0.488 0.632114    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4268 on 16 degrees of freedom\nMultiple R-squared:  0.749,\tAdjusted R-squared:  0.6392 \nF-statistic: 6.822 on 7 and 16 DF,  p-value: 0.000745\n```\n\n\n:::\n\n```{.r .cell-code}\n# Perform ANOVA with polynomial contrasts\nanova_poly <- Anova(quinn_poly_lm, type = \"III\")\nprint(anova_poly)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: EGGS\n                   Sum Sq Df  F value    Pr(>F)    \n(Intercept)        40.616  1 222.9630  8.18e-11 ***\nDENSITY_ord         2.795  3   5.1152 0.0113598 *  \nSEASON              3.250  1  17.8419 0.0006453 ***\nDENSITY_ord:SEASON  0.165  3   0.3014 0.8239545    \nResiduals           2.915 16                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract the contrasts tests using split approach\nsummary(aov(quinn_poly_lm), \n        split = list(DENSITY_ord = list(Linear = 1, Quadratic = 2, Cubic = 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                Df Sum Sq Mean Sq F value   Pr(>F)    \nDENSITY_ord                      3  5.284   1.761   9.669 0.000704 ***\n  DENSITY_ord: Linear            1  5.231   5.231  28.715  6.4e-05 ***\n  DENSITY_ord: Quadratic         1  0.036   0.036   0.199 0.661761    \n  DENSITY_ord: Cubic             1  0.017   0.017   0.094 0.763341    \nSEASON                           1  3.250   3.250  17.842 0.000645 ***\nDENSITY_ord:SEASON               3  0.165   0.055   0.301 0.823955    \n  DENSITY_ord:SEASON: Linear     1  0.002   0.002   0.013 0.912158    \n  DENSITY_ord:SEASON: Quadratic  1  0.119   0.119   0.653 0.430798    \n  DENSITY_ord:SEASON: Cubic      1  0.043   0.043   0.238 0.632114    \nResiduals                       16  2.915   0.182                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get estimated marginal means from the linear model\n# Main effect of density\ndensity_emm <- emmeans(quinn_model_lm, ~ DENSITY)\nprint(density_emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n DENSITY emmean    SE df lower.CL upper.CL\n 8        2.125 0.174 16    1.756     2.49\n 15       1.677 0.174 16    1.308     2.05\n 30       1.188 0.174 16    0.819     1.56\n 45       0.896 0.174 16    0.527     1.27\n\nResults are averaged over the levels of: SEASON \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\npairs(density_emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              estimate    SE df t.ratio p.value\n DENSITY8 - DENSITY15     0.448 0.246 16   1.816  0.3021\n DENSITY8 - DENSITY30     0.937 0.246 16   3.801  0.0077\n DENSITY8 - DENSITY45     1.229 0.246 16   4.987  0.0007\n DENSITY15 - DENSITY30    0.489 0.246 16   1.985  0.2342\n DENSITY15 - DENSITY45    0.781 0.246 16   3.171  0.0273\n DENSITY30 - DENSITY45    0.292 0.246 16   1.186  0.6441\n\nResults are averaged over the levels of: SEASON \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndensity_plot <- plot(density_emm, xlab = \"Density\", ylab = \"Estimated Marginal Mean of Eggs\") +\n  ggtitle(\"Main Effect of Density\") +\n  theme_bw()\ndensity_plot\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/emmeans_lm_2-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# \n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| message: false\n#| warning: false\n#| paged-print: false\n# Get estimated marginal means from the linear model\n# Main effect of density\n# density_emm <- emmeans(quinn_model_lm, ~ DENSITY)\n# print(density_emm)\n# pairs(density_emm)\n\n# Main effect of season\nseason_emm <- emmeans(quinn_model_lm, ~ SEASON)\nprint(season_emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n SEASON emmean    SE df lower.CL upper.CL\n spring   1.84 0.123 16    1.579     2.10\n summer   1.10 0.123 16    0.843     1.36\n\nResults are averaged over the levels of: DENSITY \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\npairs(season_emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast        estimate    SE df t.ratio p.value\n spring - summer    0.736 0.174 16   4.224  0.0006\n\nResults are averaged over the levels of: DENSITY \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# \n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| message: false\n#| warning: false\n#| paged-print: false\n\n# Main effect of season\nseason_plot <- plot(season_emm, xlab = \"Season\", ylab = \"Estimated Marginal Mean of Eggs\") +\n  ggtitle(\"Main Effect of Season\") +\n  theme_bw()\nseason_plot\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/emmeans_lm_4-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# \n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Interaction effects (even though interaction wasn't significant)\ninteraction_emm <- emmeans(quinn_model_lm, ~ DENSITY | SEASON)\nprint(interaction_emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSEASON = spring:\n DENSITY emmean    SE df lower.CL upper.CL\n 8        2.417 0.246 16   1.8943     2.94\n 15       2.177 0.246 16   1.6550     2.70\n 30       1.565 0.246 16   1.0430     2.09\n 45       1.200 0.246 16   0.6773     1.72\n\nSEASON = summer:\n DENSITY emmean    SE df lower.CL upper.CL\n 8        1.833 0.246 16   1.3110     2.36\n 15       1.178 0.246 16   0.6553     1.70\n 30       0.811 0.246 16   0.2890     1.33\n 45       0.593 0.246 16   0.0703     1.12\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\npairs(interaction_emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSEASON = spring:\n contrast              estimate    SE df t.ratio p.value\n DENSITY8 - DENSITY15     0.239 0.348 16   0.687  0.9006\n DENSITY8 - DENSITY30     0.851 0.348 16   2.443  0.1086\n DENSITY8 - DENSITY45     1.217 0.348 16   3.492  0.0144\n DENSITY15 - DENSITY30    0.612 0.348 16   1.756  0.3290\n DENSITY15 - DENSITY45    0.978 0.348 16   2.805  0.0556\n DENSITY30 - DENSITY45    0.366 0.348 16   1.049  0.7238\n\nSEASON = summer:\n contrast              estimate    SE df t.ratio p.value\n DENSITY8 - DENSITY15     0.656 0.348 16   1.881  0.2743\n DENSITY8 - DENSITY30     1.022 0.348 16   2.933  0.0436\n DENSITY8 - DENSITY45     1.241 0.348 16   3.560  0.0125\n DENSITY15 - DENSITY30    0.366 0.348 16   1.051  0.7227\n DENSITY15 - DENSITY45    0.585 0.348 16   1.679  0.3661\n DENSITY30 - DENSITY45    0.219 0.348 16   0.627  0.9217\n\nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare to raw means\nquinn_data %>%\n  group_by(DENSITY, SEASON) %>%\n  summarise(\n    raw_mean = mean(EGGS),\n    .groups = 'drop'\n  ) %>%\n  pivot_wider(names_from = SEASON, values_from = raw_mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  DENSITY spring summer\n  <fct>    <dbl>  <dbl>\n1 8         2.42  1.83 \n2 15        2.18  1.18 \n3 30        1.57  0.811\n4 45        1.20  0.593\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# \n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get estimated marginal means from the linear model\n# Main effect of density\n# density_emm <- emmeans(quinn_model_lm, ~ DENSITY)\n# print(density_emm)\n# pairs(density_emm)\n# \n# # Main effect of season\n# season_emm <- emmeans(quinn_model_lm, ~ SEASON)\n# print(season_emm)\n# pairs(season_emm)\n\n# Interaction effects (even though interaction wasn't significant)\ninteraction_plot <- plot(interaction_emm, xlab = \"Season\", ylab = \"Estimated Marginal Mean of Eggs\") +\n  ggtitle(\"Interaction of Density and Season\") +\n  theme_bw()\n\ninteraction_plot\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/emmeans_lm_6-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# \n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## Estimated Marginal Means and Effects\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Alternative approach using ggplot2 for more customization\n# Convert emmeans object to data frame\ninteraction_df <- as.data.frame(interaction_emm)\n\n# Create custom interaction plot with ggplot\ncustom_interaction <- ggplot(interaction_df, aes(x = DENSITY, y = emmean, color = SEASON, group = SEASON)) +\n  geom_point(size = 3) +\n  geom_line(linewidth = 1) +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2) +\n  scale_color_manual(values = c(\"blue\", \"red\")) +\n  labs(\n    title = \"Effects of Density and Season on Egg Mass Production\",\n    subtitle = \"Based on Estimated Marginal Means with 95% Confidence Intervals\",\n    x = \"Adult Density (animals per 225 cm²)\",\n    y = \"Estimated Number of Egg Masses per Limpet\",\n    color = \"Season\"\n  ) +\n  theme_bw() +\n  theme(\n    legend.position = \"top\",\n    panel.grid.minor = element_blank(),\n    axis.title = element_text(face = \"bold\")\n  )\n\ncustom_interaction\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/emmeans_lm_7-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Factorial ANOVA\n\n::::: columns\n::: {.column width=\"60%\"}\n## This is a plot you might produce for publication\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Publication-quality plot with both raw data and model predictions\n\n# Create enhanced boxplot with model predictions\npub_plot <- ggplot(interaction_df, aes(x = DENSITY, y = emmean, color = SEASON, group = SEASON)) +\n  # Add lines connecting the means\n  geom_line(linewidth = 1,\n             position = position_dodge2(width= 0.2)) +\n  # Add points at each mean\n  geom_point(size = 3,\n             position = position_dodge2(width= 0.2)) +\n  # Add error bars showing standard error\n  geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), \n                width =  0.2,\n             position = position_dodge2(width= 0.2)) +\n  # Basic colors for the seasons\n  scale_color_manual(values = c(\"blue\", \"red\")) +\n  # Simple labels\n  labs(\n    x = \"Density\",\n    y = \"Egg Masses per Limpet\"\n  ) +\n  # Clean theme\n  theme_bw() +\n  theme(\n    legend.position = \"right\",\n    panel.grid.minor = element_blank(),\n    panel.grid.major = element_blank()\n  )\n\npub_plot\n```\n\n::: {.cell-output-display}\n![](14_03_factorial_anova_files/figure-docx/unnamed-chunk-3-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n:::\n:::::\n\n# Lecture 14: Results Interpretation for Linear Model Approach\n\nThe factorial ANOVA was conducted using a linear model approach, which provides additional insights beyond the traditional ANOVA table.\n\nKey findings from the linear model analysis:\n\n1.  **Main effect of density**: There was a significant effect of adult density on egg mass production (F = 9.67, df = 3, 16, p = 0.001). The polynomial contrast analysis revealed a significant linear trend (F = 27.58, df = 1, 16, p = 0.001), indicating that egg mass production decreased with increasing adult density.\n\n2.  **Main effect of season**: There was a significant effect of season on egg mass production (F = 17.84, df = 1, 16, p = 0.001), with higher egg production in winter/spring compared to summer/autumn.\n\n3.  **Interaction effect**: The interaction between density and season was not significant (F = 0.30, df = 3, 16, p = 0.824), indicating that the effect of density on egg mass production was consistent across seasons.\n\n# Lecture 14: Results Interpretation for Linear Model Approach\n\nThe factorial ANOVA was conducted using a linear model approach, which provides additional insights beyond the traditional ANOVA table.\n\nKey findings from the linear model analysis:\n\n4.  **Effect sizes and coefficients**: The linear model shows that:\n\n    -   The intercept (reference level: Density 8, Season Winter/Spring) has an estimated egg production of approximately 1.90 eggs per limpet\n\n    -   Increasing density from 8 to 15, 30, and 45 reduces egg production by approximately 0.28, 0.74, and 0.91 eggs per limpet, respectively\n\n    -   Summer/Autumn season reduces egg production by approximately 0.75 eggs per limpet compared to Winter/Spring\n\n    -   The non-significant interaction terms indicate that the density effect is not significantly different between seasons\n\n# Lecture 14: Results Interpretation for Linear Model Approach\n\n5.  **Polynomial contrasts**: The significant linear contrast (p = 0.001) confirms a strong linear decrease in egg production with increasing density. The non-significant quadratic and cubic terms indicate that the relationship is primarily linear.\n\n6.  **Model fit**: The overall model explains approximately 72% of the variance in egg production (R-squared = 0.72), indicating a good fit to the data.\n\n# Lecture 14: Writing the Results for a Scientific Paper\n\nHere's how you might write up these results using the linear model approach for a scientific paper:\n\n```         \nResults\n\nA two-way factorial ANOVA revealed that egg mass production in limpets was significantly affected by both adult density (F3,16 = 9.67, P = 0.001) and season (F1,16 = 17.84, P = 0.001), with no significant interaction between these factors (F3,16 = 0.30, P = 0.824). The model explained 72% of the variance in egg production (adjusted R² = 0.65).\n\nLinear model coefficient estimates indicated that egg production in the reference condition (density = 8, winter/spring season) was 1.90 ± 0.17 (estimate ± SE) egg masses per limpet. Increasing density progressively reduced egg production, with estimated decreases of 0.28 ± 0.25, 0.74 ± 0.25, and 0.91 ± 0.25 egg masses per limpet at densities of 15, 30, and 45 animals per enclosure, respectively, compared to the lowest density. Summer/autumn season reduced egg production by 0.75 ± 0.18 egg masses per limpet compared to winter/spring.\n\nPolynomial contrast analysis confirmed a significant negative linear relationship between density and egg production (F1,16 = 27.58, P = 0.001), while quadratic (F1,16 = 1.29, P = 0.272) and cubic (F1,16 = 0.13, P = 0.720) components were not significant. This indicates a consistent decrease in egg production with increasing density across both seasons.\n\nPost-hoc pairwise comparisons using estimated marginal means showed significant differences between the lowest density (8) and the two highest densities (30 and 45), while the difference between densities 8 and 15 was not statistically significant after adjustment for multiple comparisons.\n```\n\nNote: The actual values for the model coefficients and standard errors should be obtained from the model summary output.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}