{
  "hash": "afc39e4cb74410ded2e050a512ec2922",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 12 - ANOVA in class \"\nauthor: \"Bill Perry\"\nexecute:\n  freeze: auto\n  cache: true\n  echo: true\n  keep-md: true\n  fig-height: 4\n  fig-width: 6\n  paged-print: false\nformat:\n  html:\n    freeze: false\n    toc: false\n    output-file: \"12_02_class_activity.html\"\n    default: true\n    embed-resources: true\n    self-contained: true\n    max-width: 80ch\n    css: ../../css/activity.css\n  docx:\n    default: true\n    toc: false\n    toc-depth: 3\n    number-sections: false\n    highlight-style: github\n    reference-doc: ../../ms_templates/custom-reference.docx\n    css: msword.css\n    embed-resources: true\n---\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  treatment phase_shift\n  <chr>           <dbl>\n1 Control          0.53\n2 Control          0.36\n3 Control          0.2 \n4 Control         -0.37\n5 Control         -0.6 \n6 Control         -0.64\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the data\ncircadian_plot <- ggplot(circ_data, aes(x = treatment, y = phase_shift, color = treatment)) +\n  geom_point(position = position_jitter(width=0.1)) +\n  stat_summary(fun = mean, geom = \"point\", size = 5, shape = 18) +\n  stat_summary(fun.data = \"mean_cl_normal\", geom = \"errorbar\", width = 0.2) +\n  theme_minimal() +\n  labs(title = \"Circadian Rhythm Phase Shift by Treatment\",\n       x = \"Light Treatment\",\n       y = \"Phase Shift (hours)\") +\n  theme(legend.position = \"none\")\ncircadian_plot\n```\n\n::: {.cell-output-display}\n![](12_02_class_activity_files/figure-docx/plot-1.png)\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: phase_shift\n            Sum Sq Df F value   Pr(>F)   \n(Intercept) 0.7626  1  1.5389 0.229877   \ntreatment   7.2245  2  7.2894 0.004472 **\nResiduals   9.4153 19                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_02_class_activity_files/figure-docx/unnamed-chunk-3-1.png)\n:::\n:::\n\n\n\n\n\n\n# ANOVA-Assumptions and Diagnostics\n\nANOVA has the same assumptions as the two-sample t-test, but applied to\nall k groups:\n\n1.  **Random samples** from corresponding populations\\\n2.  **Normality**: Y values are normally distributed in each population\\\n3.  **Homogeneity of variance**: variance is the same in all\n    populations\\\n4.  **Independence**: observations are independent\n\n**Checking assumptions**:\n\n-   Normality: Q-Q plots, histogram of residuals, Shapiro-Wilk test\\\n-   Homogeneity: plot residuals vs. predicted values or x-values\\\n-   Independence: examine experimental design\n\n# **Lecture 12:** ANOVA diagnostics\n\nThis is the default output of base R\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_02_class_activity_files/figure-docx/unnamed-chunk-4-1.png)\n:::\n:::\n\n\n\n\n\n\n# ANOVA Diagnostics\n\nLevene's test of homogeneity of variance\\\nNull Hypothesis is that they are homogeneous\\\nSo you want a non significant result here\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2  0.1586 0.8545\n      19               \n```\n\n\n:::\n:::\n\n\n\n\n\n\n# **Lecture 12:** ANOVA Diagnostics\n\nShapiro-Wilk Normality Test Null Hypothesis is that they are normally\ndistributed\\\nSo you want a **non significant** result here\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(model)\nW = 0.95893, p-value = 0.468\n```\n\n\n:::\n:::\n\n\n\n\n\n\n# **Lecture 12:** ANOVA Post-Hoc Testing\n\nWhen ANOVA rejects H₀, we need to determine which groups differ.\n\n**Example**: Using Tukey's HSD to compare all pairs of treatments in the\ncircadian rhythm data. \n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast        estimate    SE df t.ratio p.value\n Control - Eyes     1.243 0.364 19   3.411  0.0088\n Control - Knees    0.027 0.364 19   0.074  0.9998\n Eyes - Knees      -1.216 0.376 19  -3.231  0.0131\n\nP value adjustment: sidak method for 3 tests \n```\n\n\n:::\n:::\n\n\n\n\n\n\n# NEED TO CHECk THIS\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n treatment emmean    SE df lower.CL upper.CL .group\n Eyes      -1.551 0.266 19    -2.25   -0.855  a    \n Knees     -0.336 0.266 19    -1.03    0.361   b   \n Control   -0.309 0.249 19    -0.96    0.343   b   \n\nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 3 estimates \nP value adjustment: sidak method for 3 tests \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n\n\n\n\n# **Lecture 12:** ANOVA Post-Hoc Testing\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_02_class_activity_files/figure-docx/unnamed-chunk-9-1.png)\n:::\n:::\n\n\n\n\n\n\n# **Lecture 12:** ANOVA Post-Hoc Testing\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_02_class_activity_files/figure-docx/unnamed-chunk-10-1.png)\n:::\n:::\n\n\n\n\n\n\n# **Lecture 12:** ANOVA Reporting results\n\n**Formal scientific writing example:**\n\n\"The effect of light treatment on circadian rhythm phase shift was\nanalyzed using a one-way ANOVA. There was a significant effect of\ntreatment on phase shift (F(2, 19) = 7.29, p = 0.004, η² = 0.43).\nPost-hoc comparisons using Tukey's HSD test indicated that the mean\nphase shift for the Eyes treatment (M = -1.55 h, SD = 0.71) was\nsignificantly different from both the Control treatment (M = -0.31 h, SD\n= 0.62) and the Knees treatment (M = -0.34 h, SD = 0.79). However, the\nControl and Knees treatments did not significantly differ from each\nother. These results suggest that light exposure to the eyes, but not to\nthe knees, impacts circadian rhythm phase shifts.\"\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}