{
  "hash": "27d9c4ea6f158993e96789fdb1f87781",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 14 - NESTED ANOVA\"\nauthor: \"Bill Perry\"\nexecute:\n  freeze: auto\n  cache: true\n  echo: true\n  keep-md: true\n  message: false\n  warning: false\n  fig-height: 5\n  fig-width: 4\n  paged-print: false\nformat:\n  html:\n    toc: false\n    output-file: \"14_02_nested_anova_html.html\"\n    embed-resources: true\n    self-contained: true\n    max-width: 80ch\n    css: ../../css/lecture.css\n  revealjs:\n    output-file: \"14_02_nested_anova_slides.html\"\n    self-contained: true\n    css: ../../css/lecture.css\n    slide-number: true\n    transition: fade\n  docx:\n    default: true\n    toc: false\n    toc-depth: 3\n    number-sections: true\n    highlight-style: github\n    reference-doc: ../../ms_templates/custom-reference.docx\n    css: msword.css\n    embed-resources: true\n  pptx:\n    reference-doc: ../../ms_templates/lecture_template.pptx \n    embed-resources: true\neditor: visual\n---\n\n\n\n\n\n\n\n\n# Lecture 14: Introduction top a nested design the hard way\n\nThis analysis examines the effects of varying sea urchin densities on the percentage cover of filamentous algae. The experiment was designed with four urchin density treatments (control, 66% of original density, 33% of original density, and all urchins removed) nested within four random patches. Five replicate quadrats were measured within each treatment-patch combination.\n\n# Lecture 14: Data Overview\n\nThe dataframe contains r nrow(andrew) observations with the following variables:\n\n-   TREAT: Urchin density treatment (Control, 66% Density, 33% Density, Removed)\n-   PATCH: Random patches (1-16) where treatments were applied\n-   QUAD: Replicate quadrats within each treatment-patch combination\n-   ALGAE: Percentage cover of filamentous algae (response variable)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table with flextable\n\nsummary_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  TREAT           n  mean    sd    se   min   max\n  <fct>       <int> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 Control        20   1.3  3.18 0.711     0    13\n2 66% Density    20  21.6 25.1  5.62      0    79\n3 33% Density    20  19   25.7  5.74      0    71\n4 Removed        20  39.2 28.7  6.41      0    83\n```\n\n\n:::\n\n```{.r .cell-code}\n# \n# summary_stats %>%\n#   select(TREAT, n, mean, sd, se, min, max) %>%\n#   flextable() %>%\n#   set_header_labels(\n#     TREAT = \"Treatment\",\n#     n = \"N\",\n#     mean = \"Mean\",\n#     sd = \"SD\",\n#     se = \"SE\",\n#     min = \"Min\",\n#     max = \"Max\"\n#   ) %>%\n#   colformat_double(j = c(\"mean\", \"sd\", \"se\", \"min\", \"max\"), digits = 2) %>%\n#   autofit() %>%\n#   add_header_lines(\"Summary statistics of algae cover (%) across treatments\") %>%\n#   theme_box()\n```\n:::\n\n\n\n\n\n\n# Nested ANOVA Analysis\n\nIn this experimental design, PATCH is nested within TREAT because each patch received only one treatment level. This is a hierarchical design where the effect of patches must be considered within each treatment. Following the approach used in Quinn & Keough (2002), we'll use a traditional nested ANOVA.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n# Fit the model with treatment as fixed effect and patch nested within treatment as random\nnested_model <- lmer(ALGAE ~ TREAT + (1|TREAT:PATCH), data = andrew,\n                    control = lmerControl(optimizer = \"bobyqa\",\n                                         optCtrl = list(maxfun = 2e5)))\n# BOBYQA (Bound Optimization BY Quadratic Approximation) is an optimization algorithm used in mixed-effects modeling to find the best parameter values that maximize the likelihood function. It's especially useful when fitting complex models like the ones you're working with in your nested ANOVA analysis.\n\n# Model summary\nsummary(nested_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: ALGAE ~ TREAT + (1 | TREAT:PATCH)\n   Data: andrew\nControl: lmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 200000))\n\nREML criterion at convergence: 682.2\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.9808 -0.3106 -0.1093  0.2831  2.5910 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n TREAT:PATCH (Intercept) 294.3    17.16   \n Residual                298.6    17.28   \nNumber of obs: 80, groups:  TREAT:PATCH, 16\n\nFixed effects:\n                 Estimate Std. Error     df t value Pr(>|t|)  \n(Intercept)         1.300      9.408 12.000   0.138   0.8924  \nTREAT66% Density   20.250     13.305 12.000   1.522   0.1539  \nTREAT33% Density   17.700     13.305 12.000   1.330   0.2081  \nTREATRemoved       37.900     13.305 12.000   2.849   0.0147 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) TREAT6D TREAT3D\nTREAT66%Dns -0.707                \nTREAT33%Dns -0.707  0.500         \nTREATRemovd -0.707  0.500   0.500 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Type III ANOVA with F-statistics (not chi-square) using Satterthwaite's method\n# The issue was that you had \"type = F\" which should be \"test.statistic = 'F'\"\nanova_result <- anova(nested_model, type = 3, ddf = \"Satterthwaite\")\nprint(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \nTREAT   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Alternative using car package\n# The parameter is \"test.statistic\", not \"type\"\nanova_car <- Anova(nested_model, type = 3, test.statistic = \"F\")\nprint(anova_car)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type III Wald F tests with Kenward-Roger df)\n\nResponse: ALGAE\n                 F Df Df.res  Pr(>F)  \n(Intercept) 0.0191  1     12 0.89239  \nTREAT       2.7171  3     12 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# You could also try with the simpler model structure\nsimple_model <- lmer(ALGAE ~ TREAT + (1|PATCH), data = andrew)\nanova(simple_model, type = 3, ddf = \"Satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \nTREAT   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Method 2\n# Define your model\nmodel <- lm(ALGAE ~ TREAT + PATCH, data = andrew)\nanova_results <- anova(model)\n\n# Calculate F and p values for TREAT using PATCH as error term\nF_treat <- anova_results[\"TREAT\", \"Mean Sq\"] / anova_results[\"PATCH\", \"Mean Sq\"]\np_treat <- pf(F_treat, \n             df1 = anova_results[\"TREAT\", \"Df\"], \n             df2 = anova_results[\"PATCH\", \"Df\"],\n             lower.tail = FALSE)\n\n# Create a custom ANOVA table with the correct error terms\ncustom_anova <- data.frame(\n  Source = c(\"TREAT\", \"PATCH\", \"Residuals\"),\n  Df = anova_results[, \"Df\"],\n  \"Sum Sq\" = anova_results[, \"Sum Sq\"],\n  \"Mean Sq\" = anova_results[, \"Mean Sq\"],\n  \"F value\" = c(F_treat, anova_results[\"PATCH\", \"F value\"], NA),\n  \"Pr(>F)\" = c(p_treat, anova_results[\"PATCH\", \"Pr(>F)\"], NA)\n)\n\ncustom_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Source Df   Sum.Sq  Mean.Sq  F.value          Pr..F.\n1     TREAT  3 14429.14 4809.712 2.717102 0.0912620042021\n2     PATCH 12 21241.95 1770.162 5.928207 0.0000008322613\n3 Residuals 64 19110.40  298.600       NA              NA\n```\n\n\n:::\n:::\n\n\n\n\n\n\nCalculate Variance Components\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Print corrected results\n\n# Calculate variance components\nn_quad <- 5  # Number of quadrats per patch\nvar_comp_residual <- MS_residual\nvar_comp_patch <- (MS_patch - MS_residual) / n_quad\nvar_comp_treatment <- (MS_treat - MS_patch) / (n_quad * 4)  # 4 patches per treatment\n\n# Format variance components, showing negative values in parentheses\nvar_comp_treatment_display <- ifelse(var_comp_treatment < 0, \n                                    paste0(\"(\", format(abs(var_comp_treatment), digits = 2), \")\"),\n                                    format(var_comp_treatment, digits = 2))\n\n# Create variance components table\nvar_comp_table <- data.frame(\n  Source = c(\"Treatment\", \"Patches (treatment)\", \"Residual\"),\n  Var_comp = c(var_comp_treatment_display, \n               format(var_comp_patch, digits = 2),\n               format(var_comp_residual, digits = 2))\n)\n\nprint(var_comp_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Source Var_comp\n1           Treatment      152\n2 Patches (treatment)      294\n3            Residual      299\n```\n\n\n:::\n:::\n\n\n\n\n\n\n# Lecture 14: ANOVA Results\n\nThe nested ANOVA model is specified as:\n\n$ALGAE_{ijk} = \\mu + \\alpha_i + \\beta_{j(i)} + \\epsilon_{ijk}$\n\nWhere: - $\\mu$ is the overall mean - $\\alpha_i$ is the fixed effect of treatment $i$ - $\\beta_{j(i)}$ is the random effect of patch $j$ nested within treatment $i$ - $\\epsilon_{ijk}$ is the residual error for quadrat $k$ in patch $j$ within treatment $i$\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display ANOVA results with flextable\nanova_table %>%\n  flextable() %>%\n  set_header_labels(\n    Source = \"Source of variation\",\n    df = \"df\",\n    MS = \"MS\",\n    F = \"F\",\n    p = \"p\"\n  ) %>%\n  colformat_double(j = c(\"MS\", \"F\"), digits = 2) %>%\n  autofit() %>%\n  add_header_lines(\"ANOVA table for nested design\") %>%\n  theme_box()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-ac05f23e{}.cl-ac02c636{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ac02c65e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ac040b4a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ac040b54{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ac04187e{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac04187f{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac041888{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac041889{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac041892{width:1.177in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac041893{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac041894{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac04189c{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac04189d{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac04189e{width:1.177in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418a6{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418a7{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418a8{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418a9{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418b0{width:1.177in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418b1{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418b2{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418b3{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418ba{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac0418bb{width:1.177in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-ac05f23e'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"5\"class=\"cl-ac04187e\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c636\">ANOVA table for nested design</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-ac04187e\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c636\">Source of variation</span></p></th><th class=\"cl-ac04187f\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c636\">df</span></p></th><th class=\"cl-ac041888\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c636\">MS</span></p></th><th class=\"cl-ac041889\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c636\">F</span></p></th><th class=\"cl-ac041892\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c636\">p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac041893\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c65e\">Treatment</span></p></td><td class=\"cl-ac041894\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">3</span></p></td><td class=\"cl-ac04189c\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">4,809.71</span></p></td><td class=\"cl-ac04189d\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">2.72</span></p></td><td class=\"cl-ac04189e\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c65e\">0.091262004</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac0418a6\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c65e\">Patches (treatment)</span></p></td><td class=\"cl-ac0418a7\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">12</span></p></td><td class=\"cl-ac0418a8\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">1,770.16</span></p></td><td class=\"cl-ac0418a9\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">5.93</span></p></td><td class=\"cl-ac0418b0\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c65e\">&lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac0418b1\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c65e\">Residual</span></p></td><td class=\"cl-ac0418b2\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">64</span></p></td><td class=\"cl-ac0418b3\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\">298.60</span></p></td><td class=\"cl-ac0418ba\"><p class=\"cl-ac040b54\"><span class=\"cl-ac02c65e\"></span></p></td><td class=\"cl-ac0418bb\"><p class=\"cl-ac040b4a\"><span class=\"cl-ac02c65e\"></span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\n\n# Lecture 14: Variance Components\n\nThe nested ANOVA model is specified as: $ALGAE_{ijk} = \\mu + \\alpha_i + \\beta_{j(i)} + \\epsilon_{ijk}$ Where:\n\n$\\mu$ is the overall mean $\\alpha_i$ is the fixed effect of treatment $i$ $\\beta_{j(i)}$ is the random effect of patch $j$ nested within treatment $i$ $\\epsilon_{ijk}$ is the residual error for quadrat $k$ in patch $j$ within treatment $i$\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display variance components with flextable\nvar_comp_table %>%\n  flextable() %>%\n  set_header_labels(\n    Source = \"Source of variation\",\n    Var_comp = \"Variance component\"\n  ) %>%\n  autofit() %>%\n  add_header_lines(\"Variance components\") %>%\n  theme_box()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-ac132fbc{}.cl-ac105256{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ac105260{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ac117604{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ac11819e{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac11819f{width:1.687in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac1181a8{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac1181a9{width:1.687in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac1181aa{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac1181b2{width:1.687in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac1181b3{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac1181b4{width:1.687in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-ac132fbc'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"2\"class=\"cl-ac11819e\"><p class=\"cl-ac117604\"><span class=\"cl-ac105256\">Variance components</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-ac11819e\"><p class=\"cl-ac117604\"><span class=\"cl-ac105256\">Source of variation</span></p></th><th class=\"cl-ac11819f\"><p class=\"cl-ac117604\"><span class=\"cl-ac105256\">Variance component</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac1181a8\"><p class=\"cl-ac117604\"><span class=\"cl-ac105260\">Treatment</span></p></td><td class=\"cl-ac1181a9\"><p class=\"cl-ac117604\"><span class=\"cl-ac105260\">152</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac1181aa\"><p class=\"cl-ac117604\"><span class=\"cl-ac105260\">Patches (treatment)</span></p></td><td class=\"cl-ac1181b2\"><p class=\"cl-ac117604\"><span class=\"cl-ac105260\">294</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac1181b3\"><p class=\"cl-ac117604\"><span class=\"cl-ac105260\">Residual</span></p></td><td class=\"cl-ac1181b4\"><p class=\"cl-ac117604\"><span class=\"cl-ac105260\">299</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\n\n::: {.callout-important appearance=\"simple\"}\nInterpretation of ANOVA Results The nested ANOVA reveals that there was no significant effect of urchin density treatment on algae cover (F = r round(F_treat, 2), df = r df_treat, r df_patch, p = r format(p_treat, digits=3)). However, there was significant variation among patches within treatments (F = r round(F_patch, 2), df = r df_patch, r df_residual, p \\< 0.001). The variance component for patches nested within treatments (r format(var_comp_patch, digits=2)) indicates substantial spatial heterogeneity in algae cover, highlighting the importance of accounting for this spatial variation in the analysis.\n:::\n\n# Lecture 14: Post-hoc Comparisons\n\nAlthough the main effect of treatment was not significant in the nested ANOVA (p = r format(p_treat, digits=3)), we can still examine the mean differences between treatments to understand patterns in the data. However, we should interpret these with caution given the lack of statistical significance at the α = 0.05 level.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate estimated marginal means\nemm <- emmeans(nested_model, ~ TREAT)\n\n# Display EMMs with flextable\nas.data.frame(summary(emm)) %>%\n  flextable() %>%\n  set_header_labels(\n    TREAT = \"Treatment\",\n    emmean = \"Estimated Marginal Mean\",\n    SE = \"Standard Error\",\n    df = \"df\",\n    lower.CL = \"Lower CL\",\n    upper.CL = \"Upper CL\"\n  ) %>%\n  colformat_double(j = c(\"emmean\", \"SE\", \"lower.CL\", \"upper.CL\"), digits = 2) %>%\n  autofit() %>%\n  add_header_lines(\"Estimated marginal means for each treatment\") %>%\n  theme_box()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-ac314754{}.cl-ac2e2f56{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ac2e2f60{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ac2f692a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ac2f6934{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ac2f7712{width:1.143in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7713{width:2.017in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f771c{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f771d{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f771e{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7726{width:1.143in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7727{width:2.017in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7730{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7731{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f773a{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7744{width:1.143in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7745{width:2.017in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7746{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f774e{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f774f{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7758{width:1.143in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7759{width:2.017in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7762{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7763{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ac2f7764{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-ac314754'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"6\"class=\"cl-ac2f7712\"><p class=\"cl-ac2f692a\"><span class=\"cl-ac2e2f56\">Estimated marginal means for each treatment</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-ac2f7712\"><p class=\"cl-ac2f692a\"><span class=\"cl-ac2e2f56\">Treatment</span></p></th><th class=\"cl-ac2f7713\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f56\">Estimated Marginal Mean</span></p></th><th class=\"cl-ac2f771c\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f56\">Standard Error</span></p></th><th class=\"cl-ac2f771d\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f56\">df</span></p></th><th class=\"cl-ac2f771e\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f56\">Lower CL</span></p></th><th class=\"cl-ac2f771e\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f56\">Upper CL</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac2f7726\"><p class=\"cl-ac2f692a\"><span class=\"cl-ac2e2f60\">Control</span></p></td><td class=\"cl-ac2f7727\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">1.30</span></p></td><td class=\"cl-ac2f7730\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">9.41</span></p></td><td class=\"cl-ac2f7731\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">12</span></p></td><td class=\"cl-ac2f773a\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">-19.20</span></p></td><td class=\"cl-ac2f773a\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">21.80</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac2f7744\"><p class=\"cl-ac2f692a\"><span class=\"cl-ac2e2f60\">66% Density</span></p></td><td class=\"cl-ac2f7745\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">21.55</span></p></td><td class=\"cl-ac2f7746\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">9.41</span></p></td><td class=\"cl-ac2f774e\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">12</span></p></td><td class=\"cl-ac2f774f\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">1.05</span></p></td><td class=\"cl-ac2f774f\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">42.05</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac2f7744\"><p class=\"cl-ac2f692a\"><span class=\"cl-ac2e2f60\">33% Density</span></p></td><td class=\"cl-ac2f7745\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">19.00</span></p></td><td class=\"cl-ac2f7746\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">9.41</span></p></td><td class=\"cl-ac2f774e\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">12</span></p></td><td class=\"cl-ac2f774f\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">-1.50</span></p></td><td class=\"cl-ac2f774f\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">39.50</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ac2f7758\"><p class=\"cl-ac2f692a\"><span class=\"cl-ac2e2f60\">Removed</span></p></td><td class=\"cl-ac2f7759\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">39.20</span></p></td><td class=\"cl-ac2f7762\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">9.41</span></p></td><td class=\"cl-ac2f7763\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">12</span></p></td><td class=\"cl-ac2f7764\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">18.70</span></p></td><td class=\"cl-ac2f7764\"><p class=\"cl-ac2f6934\"><span class=\"cl-ac2e2f60\">59.70</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\n\n\n# Lecture 14: Tukey Pairwise Comparisons\n\n-   text\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pairwise comparisons with Tukey adjustment\npairs <- pairs(emm, adjust = \"tukey\")\npairs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                  estimate   SE df t.ratio p.value\n Control - 66% Density       -20.25 13.3 12  -1.522  0.4553\n Control - 33% Density       -17.70 13.3 12  -1.330  0.5625\n Control - Removed           -37.90 13.3 12  -2.849  0.0615\n 66% Density - 33% Density     2.55 13.3 12   0.192  0.9974\n 66% Density - Removed       -17.65 13.3 12  -1.327  0.5646\n 33% Density - Removed       -20.20 13.3 12  -1.518  0.4573\n\nDegrees-of-freedom method: kenward-roger \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\n# # Display pairwise comparisons with flextable\n# as.data.frame(summary(pairs)) %>%\n#   flextable() %>%\n#   set_header_labels(\n#     contrast = \"Contrast\",\n#     estimate = \"Estimate\",\n#     SE = \"Standard Error\",\n#     df = \"df\",\n#     t.ratio = \"t ratio\",\n#     p.value = \"p-value\"\n#   ) %>%\n#   colformat_double(j = c(\"estimate\", \"SE\", \"t.ratio\", \"p.value\"), digits = 3) %>%\n#   autofit() %>%\n#   add_header_lines(\"Pairwise comparisons between treatments (Tukey-adjusted)\") %>%\n#   theme_box()\n```\n:::\n\n\n\n\n\n\n# Lecture 14: Letter Display\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract compact letter display for plotting\ncld <- multcomp::cld(emm, alpha = 0.05, Letters = letters)\n\ncld\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n TREAT       emmean   SE df lower.CL upper.CL .group\n Control        1.3 9.41 12   -19.20     21.8  a    \n 33% Density   19.0 9.41 12    -1.50     39.5  a    \n 66% Density   21.6 9.41 12     1.05     42.0  a    \n Removed       39.2 9.41 12    18.70     59.7  a    \n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 4 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n\n```{.r .cell-code}\n# # Display CLD with flextable\n# as.data.frame(cld) %>%\n#   flextable() %>%\n#   set_header_labels(\n#     TREAT = \"Treatment\",\n#     emmean = \"Estimated Marginal Mean\",\n#     SE = \"Standard Error\",\n#     df = \"df\",\n#     lower.CL = \"Lower CL\",\n#     upper.CL = \"Upper CL\",\n#     .group = \"Group\"\n#   ) %>%\n#   colformat_double(j = c(\"emmean\", \"SE\", \"lower.CL\", \"upper.CL\"), digits = 2) %>%\n#   autofit() %>%\n#   add_header_lines(\"Compact letter display of treatment means\") %>%\n#   theme_box()\n```\n:::\n\n\n\n\n\n\n::: {.callout-important appearance=\"simple\"}\nInterpretation of Treatment Comparisons The mean algae cover for the Control treatment (1.30%) appears considerably lower than for the reduced urchin density treatments (66% Density: 21.55%, 33% Density: 19.00%, Removed: 39.20%). While the visual pattern suggests an inverse relationship between urchin density and algae cover, with complete removal showing the highest algae cover, the nested ANOVA showed that these differences were not statistically significant at the α = 0.05 level (p = r format(p_treat, digits=3)). The high variability among patches within treatments likely contributed to the lack of statistical significance for the treatment effect.\n:::\n\n# Lecture 14: ANOVA Assumptions Testing\n\nFor valid inference from ANOVA, several assumptions must be met. We test these assumptions below.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract residuals\nresiduals <- residuals(nested_model)\n\n# QQ plot\nqq_plot <- ggplot(data.frame(residuals = residuals), aes(sample = residuals)) +\n  stat_qq() +\n  stat_qq_line() +\n  # theme_cowplot() +\n  labs(title = \"Normal Q-Q Plot of Residuals\",\n       x = \"Theoretical Quantiles\",\n       y = \"Sample Quantiles\")\n\n# Histogram of residuals\nhist_plot <- ggplot(data.frame(residuals = residuals), aes(x = residuals)) +\n  geom_histogram(bins = 15, fill = \"lightblue\", color = \"black\") +\n  # theme_cowplot() +\n  labs(title = \"Histogram of Residuals\",\n       x = \"Residuals\",\n       y = \"Frequency\")\n\n# Residuals vs. Fitted plot\nfitted_values <- fitted(nested_model)\nresid_plot <- ggplot(data.frame(fitted = fitted_values, residuals = residuals), \n                    aes(x = fitted, y = residuals)) +\n  geom_point() +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  # theme_cowplot() +\n  labs(title = \"Residuals vs. Fitted Values\",\n       x = \"Fitted Values\",\n       y = \"Residuals\")\n\n# Combine plots\nqq_plot + hist_plot + resid_plot + plot_layout(ncol = 3)\n```\n\n::: {.cell-output-display}\n![](14_02_nested_anova_files/figure-html/unnamed-chunk-8-1.png){width=384}\n:::\n:::\n\n\n\n\n\n\n# Lecture 14: Levenes Test for Homogeneity of Variance\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Homogeneity of Variance\n# Levene's test\n# Levene's test for homogeneity of variance\nlevene_test <- leveneTest(ALGAE ~ TREAT, data = andrew)\nlevene_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value     Pr(>F)    \ngroup  3  8.1694 0.00008785 ***\n      76                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# # Display results with flextable\n# data.frame(\n#   Statistic = c(levene_test$`F value`[1]),\n#   df1 = c(levene_test$Df[1]),\n#   df2 = c(levene_test$Df[2]),\n#   p.value = c(levene_test$`Pr(>F)`[1])\n# ) %>%\n#   flextable() %>%\n#   set_header_labels(\n#     Statistic = \"F value\",\n#     df1 = \"df1\",\n#     df2 = \"df2\",\n#     p.value = \"p-value\"\n#   ) %>%\n#   colformat_double(j = c(\"Statistic\", \"p.value\"), digits = 3) %>%\n#   autofit() %>%\n#   add_header_lines(\"Levene's Test for Homogeneity of Variance\") %>%\n#   theme_box()\n```\n:::\n\n\n\n\n\n\n::: {.callout-important appearance=\"simple\"}\nInterpretation of Assumption Tests The Q-Q plot shows some deviation from normality, particularly in the tails, and Levene's test indicates significant heterogeneity of variances across treatments (F = r round(levene_test\\$\"F value\"\\[1\\], 2), p \\< 0.001). As noted by Quinn & Keough (2002), there were \"large differences in within-cell variances\" in this dataset, and transformations (including arcsin) did not improve variance homogeneity. However, ANOVA is generally robust to heteroscedasticity with balanced designs, which is why they chose to analyze untransformed data. The residuals vs. fitted plot also shows a pattern of increasing variance with increasing fitted values, confirming the heteroscedasticity.\n:::\n\n# Lecture 14: Visualization\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplot\nggplot_boxplot <- ggplot(andrew, aes(x = TREAT, y = ALGAE, fill = TREAT)) +\n  geom_boxplot(alpha = 0.7, outlier.shape = NA) +\n  geom_jitter(width = 0.2, alpha = 0.4, size = 1) +\n  scale_fill_viridis_d(option = \"D\", end = 0.85) +\n  labs(\n    title = \"Effect of Urchin Density on Filamentous Algae Cover\",\n    x = \"Urchin Density Treatment\",\n    y = \"Filamentous Algae Cover (%)\",\n    caption = \"Figure 1: Boxplots showing the distribution of algal cover across urchin density treatments.\\nDespite visual differences, the treatment effect was not statistically significant (p = 0.091).\"\n  ) +\n  # theme_cowplot() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\", size = 12),\n    axis.text = element_text(size = 10),\n    plot.caption = element_text(hjust = 0, face = \"italic\", size = 10)\n  )\n\nprint(ggplot_boxplot)\n```\n\n::: {.cell-output-display}\n![](14_02_nested_anova_files/figure-html/unnamed-chunk-10-1.png){width=384}\n:::\n:::\n\n\n\n\n\n\n# Lecture 14: Means Plot\n\n-   text\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create means plot\nmeans_plot <- ggplot(summary_stats, aes(x = TREAT, y = mean, group = 1)) +\n  # geom_line(size = 1) +\n  geom_point(size = 3, shape = 21, fill = \"white\") +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +\n  labs(\n    title = \"Mean Algae Cover by Urchin Density Treatment\",\n    x = \"Urchin Density Treatment\",\n    y = \"Mean Filamentous Algae Cover (%)\",\n    caption = \"Figure 2: Mean (± SE) percentage cover of filamentous algae across urchin density treatments.\"\n  ) +\n  # theme_cowplot() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\", size = 12),\n    axis.text = element_text(size = 10),\n    plot.caption = element_text(hjust = 0, face = \"italic\", size = 10)\n  )\n\nprint(means_plot)\n```\n\n::: {.cell-output-display}\n![](14_02_nested_anova_files/figure-html/unnamed-chunk-11-1.png){width=384}\n:::\n:::\n\n\n\n\n\n\n# Lecture 14: Discussion\n\n::: {.callout-important appearance=\"simple\"}\nScientific Interpretation Our nested ANOVA analysis revealed substantial spatial heterogeneity in algae cover, with significant variation among patches within each treatment (p \\< 0.001). Surprisingly, the effect of urchin density treatments on filamentous algae cover was not statistically significant at the α = 0.05 level (p = 0.091), despite apparent trends in the data. The descriptive statistics show a pattern where algae cover appears to increase as urchin density decreases, with the Control treatment (mean = 1.3%) showing minimal algae cover compared to reduced density treatments (66% Density: 21.55%, 33% Density: 19.00%, and Removed: 39.20%). This pattern suggests a potential density-dependent relationship between urchin grazing and algal abundance, but the high variability among patches masked the treatment effect. The substantial variance component associated with patches nested within treatments (294.31, approximately 39.5% of total variance) underscores the importance of spatial heterogeneity in structuring algal communities. This finding highlights the necessity of accounting for spatial variability when designing and analyzing ecological field experiments. From an ecological perspective, these results suggest that while sea urchins may influence algal communities through grazing, local environmental factors and patch-specific conditions play a dominant role in determining algae cover. This has important implications for ecosystem management, as it indicates that the effects of urchin density manipulations may be context-dependent and influenced by local environmental conditions.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}