{
  "hash": "007a73640d64d2d7d127a3476139fc04",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 14 - NESTED ANOVA Visualization\"\nauthor: \"Bill Perry\"\nprefer-html: true\nexecute:\n  freeze: auto\n  cache: true\n  echo: true\n  keep-md: true\n  message: false\n  warning: false\n  fig-height: 5\n  fig-width: 4\n  paged-print: false\nformat:\n  html:\n    toc: false\n    output-file: \"14_04_nested_anova_visual_html.html\"\n    embed-resources: true\n    self-contained: true\n    max-width: 80ch\n    css: ../../css/lecture.css\n  revealjs:\n    output-file: \"14_04_nested_anovat_visual_slides.html\"\n    self-contained: true\n    css: ../../css/lecture.css\n    slide-number: true\n    transition: fade\n  docx:\n    default: true\n    toc: false\n    toc-depth: 3\n    number-sections: true\n    highlight-style: github\n    reference-doc: ../../ms_templates/custom-reference.docx\n    css: msword.css\n    embed-resources: true\n  pptx:\n    reference-doc: ../../ms_templates/lecture_template.pptx \n    embed-resources: true\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(tidyverse)\nlibrary(patchwork)\nlibrary(cowplot)\nlibrary(car)\nlibrary(lme4)\nlibrary(lmerTest)\nlibrary(emmeans)\nlibrary(knitr)\n\nlibrary(viridis)\n\n# Set theme for consistent plotting\ntheme_set(theme_cowplot())\n\n# Custom theme for consistent plotting\nmy_theme <- theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 10),\n    axis.title = element_text(size = 9),\n    axis.text = element_text(size = 8)\n  )\n```\n:::\n\n\n\n\n\n\n\n\n\n\n# Introduction\n\nThis document provides a comparison between one-way ANOVA and nested ANOVA using the `andrew` dataset from Quinn & Keough (2002). This tutorial aims to help students understand how the partitioning of variance differs between these two approaches and why accounting for nested factors is crucial in certain experimental designs.\n\nIn the `andrew` dataset, the experimental design consists of:\n\n-   Four urchin density **treatments** (`TREAT`): Control, 66% Density, 33% Density, and Removed\n-   Each treatment was replicated within four random **patches** (`PATCH`)\n-   Five replicate **quadrats** were measured within each treatment-patch combination\n-   The response variable is percentage cover of filamentous **algae**\n\n## Dataset Overview\n\nFirst, let's load and explore the dataset:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in the andrew dataset\nandrew <- read_csv(\"data/andrew.csv\")\n\n# Convert TREAT to factor with meaningful labels\nandrew$TREAT <- factor(andrew$TREAT, \n                      levels = c(\"con\", \"t0.66\", \"t0.33\", \"rem\"),\n                      labels = c(\"Control\", \"66% Density\", \"33% Density\", \"Removed\"))\n\n# Convert PATCH to factor\nandrew$PATCH <- factor(andrew$PATCH)\n\n# Display the first few rows of the dataset\nhead(andrew)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  TREAT   PATCH  QUAD ALGAE\n  <fct>   <fct> <dbl> <dbl>\n1 Control 1         1     0\n2 Control 1         2     0\n3 Control 1         3     0\n4 Control 1         4     6\n5 Control 1         5     2\n6 Control 2         1     0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate summary statistics\nsummary_stats <- andrew %>%\n  group_by(TREAT) %>%\n  summarise(\n    n = n(),\n    mean = mean(ALGAE),\n    sd = sd(ALGAE),\n    se = sd / sqrt(n),\n    min = min(ALGAE),\n    max = max(ALGAE)\n  )\n\n# Display summary statistics\nsummary_stats \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  TREAT           n  mean    sd    se   min   max\n  <fct>       <int> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 Control        20   1.3  3.18 0.711     0    13\n2 66% Density    20  21.6 25.1  5.62      0    79\n3 33% Density    20  19   25.7  5.74      0    71\n4 Removed        20  39.2 28.7  6.41      0    83\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nLet's visualize the data distribution by treatment:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplot of algae cover by treatment\nggplot(andrew, aes(x = TREAT, y = ALGAE, fill = TREAT)) +\n  geom_boxplot(alpha = 0.7, outlier.shape = NA) +\n  geom_jitter(width = 0.2, alpha = 0.4, size = 1) +\n  scale_fill_viridis_d(option = \"D\", end = 0.85) +\n  labs(\n    title = \"Effect of Urchin Density on Filamentous Algae Cover\",\n    x = \"Urchin Density Treatment\",\n    y = \"Filamentous Algae Cover (%)\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](14_04_nested_anova_visualization_files/figure-docx/visualize-data-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n# One-way ANOVA\n\nIn a one-way ANOVA, we ignore the nested structure of the data and simply compare the means of the four treatment groups.\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Fit one-way ANOVA\noneway_model <- aov(ALGAE ~ TREAT, data = andrew)\noneway_summary <- summary(oneway_model)\n\n# Display one-way ANOVA results\noneway_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nTREAT        3  14429    4810   9.059 3.36e-05 ***\nResiduals   76  40352     531                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nIn this one-way ANOVA, we find a significant effect of treatment on algae cover (F(3, 76) = 9.06, p = 0).\n\n# Nested ANOVA\n\nNow, let's run a nested ANOVA that accounts for the hierarchical structure where patches are nested within treatments.\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Fit nested ANOVA model\nnested_model <- aov(ALGAE ~ TREAT + TREAT:PATCH, data = andrew)\nnested_summary <- summary(nested_model)\n\n# Display nested ANOVA results\nnested_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nTREAT        3  14429    4810  16.108 6.58e-08 ***\nTREAT:PATCH 12  21242    1770   5.928 8.32e-07 ***\nResiduals   64  19110     299                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n**Important Note**: The ANOVA table above does not use the correct error terms for testing the treatment effect. In a nested design, the treatment effect should be tested against the patch variation, not the residual error.\n\n## Corrected Nested ANOVA with Proper F-tests\n\nLet's calculate the correct F-ratios and p-values for the nested design:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract MS values\nMS_treat <- nested_summary[[1]][\"TREAT      \", \"Mean Sq\"] \nMS_patch <- nested_summary[[1]][\"TREAT:PATCH\", \"Mean Sq\"]\nMS_residual <- nested_summary[[1]][\"Residuals\", \"Mean Sq\"]\n\n# Extract df values\ndf_treat <- nested_summary[[1]][\"TREAT      \", \"Df\"]\ndf_patch <- nested_summary[[1]][\"TREAT:PATCH\", \"Df\"]\ndf_residual <- nested_summary[[1]][\"Residuals\", \"Df\"]\n\n# Calculate correct F ratios for nested design\nF_treat <- MS_treat / MS_patch\nF_patch <- MS_patch / MS_residual\n\n# Calculate p-values using the correct denominator df\np_treat <- pf(F_treat, df_treat, df_patch, lower.tail = FALSE)\np_patch <- pf(F_patch, df_patch, df_residual, lower.tail = FALSE)\n\n# Create ANOVA table with corrected F-tests\nanova_table <- data.frame(\n  Source = c(\"Treatment\", \"Patches (within treatment)\", \"Residual\"),\n  df = c(df_treat, df_patch, df_residual),\n  SS = c(nested_summary[[1]][\"TREAT      \", \"Sum Sq\"], \n         nested_summary[[1]][\"TREAT:PATCH\", \"Sum Sq\"], \n         nested_summary[[1]][\"Residuals\", \"Sum Sq\"]),\n  MS = c(MS_treat, MS_patch, MS_residual),\n  F = c(F_treat, F_patch, NA),\n  p = c(p_treat, p_patch, NA)\n)\n\n# Format p-values\nanova_table$p <- ifelse(anova_table$p < 0.001, \"<0.001\", \n                       ifelse(is.na(anova_table$p), NA, \n                              format(anova_table$p, digits = 3)))\n\n# Display corrected ANOVA table\nanova_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      Source df       SS       MS        F        p\n1                  Treatment  3 14429.14 4809.712 2.717102 9.13e-02\n2 Patches (within treatment) 12 21241.95 1770.162 5.928207   <0.001\n3                   Residual 64 19110.40  298.600       NA     <NA>\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nWith the corrected nested ANOVA, we find:\n\n1.  The treatment effect is not significant (F = 2.72, p = 0.0913) when tested against the patch variation.\n2.  There is significant variation among patches within treatments (F = 5.93, p < 0.001)\n\nThis is a different conclusion than the one-way ANOVA, which found a significant treatment effect.\n\n# Variance Decomposition Comparison\n\n## Visual Decomposition of Variance Components\n\nFirst, let's create a visual representation of how variance is partitioned in a standard one-way ANOVA, and then contrast it with how a nested ANOVA further divides the variance components.\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Treatment means:\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  TREAT       treat_mean\n  <fct>            <dbl>\n1 Control            1.3\n2 66% Density       21.6\n3 33% Density       19  \n4 Removed           39.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"First few rows of joined patch_means:\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  TREAT       PATCH patch_mean treat_mean\n  <fct>       <fct>      <dbl>      <dbl>\n1 Control     1            1.6        1.3\n2 Control     2            0          1.3\n3 Control     3            1          1.3\n4 Control     4            2.6        1.3\n5 66% Density 5           28.4       21.6\n6 66% Density 6           36.8       21.6\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"treat_mean column is present in patch_means\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](14_04_nested_anova_visualization_files/figure-docx/visualization-of-variance-1.png)\n:::\n\n::: {.cell-output-display}\n![](14_04_nested_anova_visualization_files/figure-docx/visualization-of-variance-2.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nThe plots above visually demonstrate the key differences in how variance is partitioned between one-way and nested ANOVA:\n\n1.  **One-way ANOVA** (first plot):\n    -   Total variance is split into just two components: Among Groups (Treatment) and Within Groups (Error)\n    -   The Within Groups component includes all variation not explained by treatments\n2.  **Nested ANOVA** (second plot):\n    -   Total variance is split into three components: Among Treatments, Among Patches within Treatments, and Within Patches (Residual Error)\n    -   The important addition is the \"Among Patches within Treatments\" component, which captures the spatial heterogeneity\n    -   The actual residual error (Within Patches) is smaller than the Within Groups error in one-way ANOVA\n\nThis visualization demonstrates why we get different conclusions: in one-way ANOVA, the patch-to-patch variation is incorrectly included in the error term, leading to an artificially inflated F-ratio for treatments.\n\n## Numerical Decomposition of Variance\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate sums of squares for both models\nSS_Total <- sum(nested_summary[[1]][, \"Sum Sq\"])\nSS_Treatment <- nested_summary[[1]][\"TREAT      \", \"Sum Sq\"]\nSS_Patch_within_Treatment <- nested_summary[[1]][\"TREAT:PATCH\", \"Sum Sq\"]\nSS_Error_Nested <- nested_summary[[1]][\"Residuals\", \"Sum Sq\"]\nSS_Error_OneWay <- oneway_summary[[1]][\"Residuals\", \"Sum Sq\"]\n\n# Calculate percentages for visualization\npercent_treatment_oneway <- (SS_Treatment / SS_Total) * 100\npercent_error_oneway <- (SS_Error_OneWay / SS_Total) * 100\n\npercent_treatment_nested <- (SS_Treatment / SS_Total) * 100\npercent_patch_nested <- (SS_Patch_within_Treatment / SS_Total) * 100\npercent_error_nested <- (SS_Error_Nested / SS_Total) * 100\n\n# Create data frame for visualization\nss_comparison <- data.frame(\n  Model = c(\n    rep(\"One-way ANOVA\", 2), \n    rep(\"Nested ANOVA\", 3)\n  ),\n  Source = c(\n    \"Treatment\", \"Error (within)\",\n    \"Treatment\", \"Patch(Treatment)\", \"Error\"\n  ),\n  Percent = c(\n    percent_treatment_oneway, percent_error_oneway,\n    percent_treatment_nested, percent_patch_nested, percent_error_nested\n  ),\n  SS = c(\n    SS_Treatment, SS_Error_OneWay,\n    SS_Treatment, SS_Patch_within_Treatment, SS_Error_Nested\n  )\n)\n\n# Add factor levels for ordering\nss_comparison$Source <- factor(\n  ss_comparison$Source,\n  levels = c(\"Treatment\", \"Patch(Treatment)\", \"Error\", \"Error (within)\")\n)\n\n# Create colors for the sources\nsource_colors <- c(\n  \"Treatment\" = \"#1b9e77\", \n  \"Patch(Treatment)\" = \"#d95f02\", \n  \"Error\" = \"#7570b3\",\n  \"Error (within)\" = \"#7570b3\"\n)\n\n# Create the stacked bar plot\np1 <- ggplot(ss_comparison, aes(x = Model, y = Percent, fill = Source)) +\n  geom_bar(stat = \"identity\", position = \"stack\", color = \"black\") +\n  scale_fill_manual(values = source_colors) +\n  labs(\n    title = \"Comparison of Variance Partitioning\",\n    subtitle = \"One-way vs. Nested ANOVA\",\n    x = \"\",\n    y = \"Percentage of Total Variance\",\n    fill = \"Source of Variation\"\n  ) +\n  geom_text(\n    aes(label = sprintf(\"%.1f%%\", Percent)),\n    position = position_stack(vjust = 0.5),\n    color = \"white\",\n    fontface = \"bold\"\n  ) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    legend.position = \"right\",\n    axis.text.x = element_text(face = \"bold\", size = 12)\n  )\n\n# Create a pie chart version for one-way ANOVA\noneway_data <- ss_comparison %>% filter(Model == \"One-way ANOVA\")\noneway_data$ypos <- cumsum(oneway_data$Percent) - 0.5 * oneway_data$Percent\n\np2 <- ggplot(oneway_data, aes(x = \"\", y = Percent, fill = Source)) +\n  geom_bar(stat = \"identity\", width = 1, color = \"black\") +\n  coord_polar(\"y\", start = 0) +\n  labs(\n    title = \"One-way ANOVA\",\n    subtitle = \"Variance Components\",\n    fill = \"Source of Variation\"\n  ) +\n  scale_fill_manual(values = source_colors) +\n  geom_text(\n    aes(y = ypos, label = sprintf(\"%.1f%%\", Percent)),\n    color = \"white\",\n    fontface = \"bold\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5),\n    legend.position = \"bottom\"\n  )\n\n# Create a pie chart version for nested ANOVA\nnested_data <- ss_comparison %>% filter(Model == \"Nested ANOVA\")\nnested_data$ypos <- cumsum(nested_data$Percent) - 0.5 * nested_data$Percent\n\np3 <- ggplot(nested_data, aes(x = \"\", y = Percent, fill = Source)) +\n  geom_bar(stat = \"identity\", width = 1, color = \"black\") +\n  coord_polar(\"y\", start = 0) +\n  labs(\n    title = \"Nested ANOVA\",\n    subtitle = \"Variance Components\",\n    fill = \"Source of Variation\"\n  ) +\n  scale_fill_manual(values = source_colors) +\n  geom_text(\n    aes(y = ypos, label = sprintf(\"%.1f%%\", Percent)),\n    color = \"white\",\n    fontface = \"bold\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5),\n    legend.position = \"bottom\"\n  )\n\n# Display all plots\np1\n```\n\n::: {.cell-output-display}\n![](14_04_nested_anova_visualization_files/figure-docx/variance-components-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine the pie charts\np2 + p3 + plot_layout(ncol = 2)\n```\n\n::: {.cell-output-display}\n![](14_04_nested_anova_visualization_files/figure-docx/pie-charts-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n# Mixed-Effects Model Approach\n\nA modern way to analyze nested designs is to use mixed-effects models. Let's compare the results with our previous analyses:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit linear mixed model with PATCH nested in TREAT\nmixed_model <- lmer(ALGAE ~ TREAT + (1|TREAT:PATCH), data = andrew)\n\n# Show model summary\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: ALGAE ~ TREAT + (1 | TREAT:PATCH)\n   Data: andrew\n\nREML criterion at convergence: 682.2\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.9808 -0.3106 -0.1093  0.2831  2.5910 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n TREAT:PATCH (Intercept) 294.3    17.16   \n Residual                298.6    17.28   \nNumber of obs: 80, groups:  TREAT:PATCH, 16\n\nFixed effects:\n                 Estimate Std. Error     df t value Pr(>|t|)  \n(Intercept)         1.300      9.408 12.000   0.138   0.8924  \nTREAT66% Density   20.250     13.305 12.000   1.522   0.1539  \nTREAT33% Density   17.700     13.305 12.000   1.330   0.2081  \nTREATRemoved       37.900     13.305 12.000   2.849   0.0147 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) TREAT6D TREAT3D\nTREAT66%Dns -0.707                \nTREAT33%Dns -0.707  0.500         \nTREATRemovd -0.707  0.500   0.500 \n```\n\n\n:::\n\n```{.r .cell-code}\n# ANOVA-style results\nanova(mixed_model, type = 3, ddf = \"Satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \nTREAT   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nThe mixed model approach gives us similar conclusions to the correctly specified nested ANOVA. The treatment effect is non-significant when accounting for the nested structure of patches within treatments.\n\n# Visualizing the Nested Structure\n\nOne way to understand why we get different results is to visualize the data by patch within treatment:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate means for each patch\npatch_means <- andrew %>%\n  group_by(TREAT, PATCH) %>%\n  summarize(ALGAE_mean = mean(ALGAE), .groups = \"drop\")\n\n# Plot patch means\nggplot() +\n  # Plot patch means\n  geom_point(data = patch_means, \n             aes(x = TREAT, y = ALGAE_mean, color = PATCH),\n             position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.7),\n             size = 3) +\n  # Add treatment means\n  geom_point(data = summary_stats, \n             aes(x = TREAT, y = mean),\n             size = 5, shape = 18, color = \"black\") +\n  # Add error bars for treatment means\n  geom_errorbar(data = summary_stats,\n                aes(x = TREAT, ymin = mean - se, ymax = mean + se),\n                width = 0.2, color = \"black\", linewidth = 1) +\n  # Plot styling\n  scale_color_viridis_d(option = \"plasma\", end = 0.9) +\n  labs(\n    title = \"Nested Structure: Patch Means within Treatments\",\n    subtitle = \"Large symbols show treatment means (± SE)\",\n    x = \"Urchin Density Treatment\",\n    y = \"Mean Filamentous Algae Cover (%)\",\n    color = \"Patch\"\n  ) +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](14_04_nested_anova_visualization_files/figure-docx/nested-structure-viz-1.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nThis plot clearly shows the high variation among patches within each treatment. This patch-to-patch variation contributes substantially to the total variance, which is not accounted for in the one-way ANOVA.\n\n# F-ratio Demonstration\n\nLet's illustrate how the F-ratio for treatments differs between one-way and nested ANOVA:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame for comparison\nf_ratio_comparison <- data.frame(\n  Model = c(\"One-way ANOVA\", \"Nested ANOVA\"),\n  F_numerator = c(\"MS Treatment\", \"MS Treatment\"),\n  F_denominator = c(\"MS Residual\", \"MS Patch(Treatment)\"),\n  F_value = c(oneway_summary[[1]][1, \"F value\"], F_treat),\n  p_value = c(oneway_summary[[1]][1, \"Pr(>F)\"], p_treat)\n)\n\n# Display the comparison\nf_ratio_comparison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Model  F_numerator       F_denominator  F_value      p_value\n1 One-way ANOVA MS Treatment         MS Residual 9.058658 3.362391e-05\n2  Nested ANOVA MS Treatment MS Patch(Treatment) 2.717102 9.126200e-02\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n# Key Differences and Implications\n\nThe comparison between one-way ANOVA and nested ANOVA reveals several important differences:\n\n1.  **Variance Partitioning**:\n    -   In one-way ANOVA, all variation not explained by treatments is lumped into the \"Error\" term.\n    -   In nested ANOVA, this variation is partitioned into \"Patch(Treatment)\" and \"Error\" components.\n2.  **F-ratio for Testing Treatment Effects**:\n    -   One-way ANOVA tests treatments against residual error (MS Treatment / MS Residual).\n    -   Nested ANOVA tests treatments against patch variation (MS Treatment / MS Patch(Treatment)).\n3.  **Biological Interpretation**:\n    -   One-way ANOVA suggests significant treatment effects (p = 0).\n    -   Nested ANOVA reveals that most variation is among patches, with non-significant treatment effects (p = 0.0913).\n    -   The substantial patch variability (38.8% of total variation) masks the treatment effect when properly accounted for.\n4.  **Statistical Power and Type I Error**:\n    -   Ignoring the nested structure leads to pseudoreplication and inflated Type I error rates.\n    -   The one-way ANOVA effectively treats each quadrat as an independent sample, inflating the degrees of freedom for the error term.\n\n# Conclusion\n\nThis demonstration illustrates why accounting for hierarchical or nested structures in experimental designs is crucial for valid statistical inference. Failure to account for such structures can lead to:\n\n1.  Pseudoreplication (treating non-independent samples as independent)\n2.  Inflation of Type I error rates (finding spurious \"significant\" effects)\n3.  Incorrect partitioning of variance sources\n4.  Misleading biological interpretations\n\nIn the `andrew` dataset, the nested ANOVA reveals that spatial heterogeneity (patch-to-patch variation) is the dominant factor influencing algae cover, not the experimental treatment. This insight would be missed if only a one-way ANOVA were used.\n\n## Alternative Code for Mixed Models\n\nFor advanced users, we could also fit this as a mixed model with `lmerTest`:\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n\n# Mixed model with patches nested within treatments\nmixed_model_alt <- lmer(ALGAE ~ TREAT + (1|TREAT:PATCH), data = andrew)\nanova(mixed_model_alt, type = 3, ddf = \"Satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \nTREAT   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# We could also try a simpler random effects structure\nsimple_mixed_model <- lmer(ALGAE ~ TREAT + (1|PATCH), data = andrew)\nanova(simple_mixed_model, type = 3, ddf = \"Satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \nTREAT   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nMixed models provide a more flexible approach to handle nested designs and are the recommended approach in modern statistical practice.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}