{
  "hash": "90fc0420cdda6a1bd8ba202ecb2bd106",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 13 - Class Activity Multifactor ANOVA\"\nauthor: \"Bill Perry\"\nmetadata-files:\n  - ../../_templates/activities.yml\nformat:\n  html:\n    output-file: \"13_02_class_activity.html\"\n  typst:\n    output-file: \"13_02_class_activity.pdf\"  \n  docx:\n    output-file: \"13_02_class_activity.docx\"\n---\n\n\n\n\n\n\n\n\n\n\n# Lecture 13: Data Overview\n\nThe dataframe contains r nrow(urchin_df) observations with the following variables:\n\n-   treat: Urchin density treatment (Control, 66% Density, 33% Density, Removed)\n-   patch: Random patches (1-16) where treatments were applied\n-   QUAD: Replicate quadrats within each treatment-patch combination\n-   algae: Percentage cover of filamentous algae (response variable)\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics\nsummary_stats <- urchin_df %>%\n  group_by(treat) %>%\n  summarise(\n    n = n(),\n    mean = mean(algae),\n    sd = sd(algae),\n    se = sd / sqrt(n),\n    min = min(algae),\n    max = max(algae),\n    .groups = 'drop'\n  )\n\nsummary_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  treat       n  mean    sd    se   min   max\n  <fct>   <int> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 control    20   1.3  3.18 0.711     0    13\n2 dens_33    20  21.6 25.1  5.62      0    79\n3 dens_66    20  19   25.7  5.74      0    71\n4 removal    20  39.2 28.7  6.41      0    83\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Nested ANOVA Analysis\n\nIn this experimental design, patch is nested within treat because each patch received only one treatment level. This is a hierarchical design where the effect of patches must be considered within each treatment. Following the approach used in Quinn & Keough (2002), we'll use a traditional nested ANOVA.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# other ways using aov built in\n# This will give you the correct F-test using PATCH within TREAT as error term\nmodel_aov <- aov(algae ~ treat + Error(treat:patch), data = urchin_df)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in aov(algae ~ treat + Error(treat:patch), data = urchin_df): Error()\nmodel is singular\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nError: treat:patch\n          Df Sum Sq Mean Sq F value Pr(>F)  \ntreat      3  14429    4810   2.717 0.0913 .\nResiduals 12  21242    1770                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nError: Within\n          Df Sum Sq Mean Sq F value Pr(>F)\nResiduals 64  19110   298.6               \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using afex package (recommended for unbalanced designs)\n# The afex package is specifically designed for ANOVA with Type III SS and handles nested designs well:\n\nurchin_df$treat <- as.factor(urchin_df$treat)\n# urchin_df$PATCH_NESTED <- as.factor(urchin_df$PATCH)\n\n# This works and gives you the correct answer\nmodel_afx <- aov_car(algae ~ treat + Error(patch), \n                     data = urchin_df,\n                     fun_aggregate = mean) # note this is not the best but would work as its less powerful\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nContrasts set to contr.sum for the following variables: treat\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_afx)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: algae\n      num Df den Df    MSE      F     ges  Pr(>F)  \ntreat      3     12 354.03 2.7171 0.40451 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n# Fit the model with treatment as fixed effect and patch nested within treatment as random\nnested_model <- lmer(algae ~ treat + (1|treat:patch), data = urchin_df,\n                    control = lmerControl(optimizer = \"bobyqa\",\n                                         optCtrl = list(maxfun = 2e5)))\n# BOBYQA (Bound Optimization BY Quadratic Approximation) is an optimization algorithm used in mixed-effects modeling to find the best parameter values that maximize the likelihood function. It's especially useful when fitting complex models like the ones you're working with in your nested ANOVA analysis.\n\n# Model summary\nsummary(nested_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: algae ~ treat + (1 | treat:patch)\n   Data: urchin_df\nControl: lmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 200000))\n\nREML criterion at convergence: 682.2\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.9808 -0.3106 -0.1093  0.2831  2.5910 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n treat:patch (Intercept) 294.3    17.16   \n Residual                298.6    17.28   \nNumber of obs: 80, groups:  treat:patch, 16\n\nFixed effects:\n             Estimate Std. Error     df t value Pr(>|t|)  \n(Intercept)     1.300      9.408 12.000   0.138   0.8924  \ntreatdens_33   20.250     13.305 12.000   1.522   0.1539  \ntreatdens_66   17.700     13.305 12.000   1.330   0.2081  \ntreatremoval   37.900     13.305 12.000   2.849   0.0147 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) trt_33 trt_66\ntreatdns_33 -0.707              \ntreatdns_66 -0.707  0.500       \ntreatremovl -0.707  0.500  0.500\n```\n\n\n:::\n\n```{.r .cell-code}\n# Type III ANOVA with F-statistics (not chi-square) using Satterthwaite's method\n# The issue was that you had \"type = F\" which should be \"test.statistic = 'F'\"\nanova_result <- anova(nested_model, type = 3, ddf = \"Satterthwaite\")\nprint(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \ntreat   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Alternative using car package\n# The parameter is \"test.statistic\", not \"type\"\nanova_car <- Anova(nested_model, type = 3, test.statistic = \"F\")\nprint(anova_car)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type III Wald F tests with Kenward-Roger df)\n\nResponse: algae\n                 F Df Df.res  Pr(>F)  \n(Intercept) 0.0191  1     12 0.89239  \ntreat       2.7171  3     12 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# You could also try with the simpler model structure\nsimple_model <- lmer(algae ~ treat + (1|patch), data = urchin_df)\nmodel_satterwait <- anova(simple_model, type = 3, ddf = \"Satterthwaite\")\nmodel_satterwait\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \ntreat   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: ANOVA Results\n\nThe nested ANOVA model is specified as:\n\n$algae_{ijk} = \\mu + \\alpha_i + \\beta_{j(i)} + \\epsilon_{ijk}$\n\nWhere:\n\n-   \\- $\\mu$ is the overall mean\n-   \\- $\\alpha_i$ is the fixed effect of treatment $i$\n-   \\- $\\beta_{j(i)}$ is the random effect of patch $j$ nested within treatment $i$\n-   \\- $\\epsilon_{ijk}$ is the residual error for quadrat $k$ in patch $j$ within treatment $i$\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_satterwait\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \ntreat   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: Post-hoc Comparisons\n\nAlthough the main effect of treatment was not significant in the nested ANOVA (p = r format(p_treat, digits=3)), we can still examine the mean differences between treatments to understand patterns in the data. However, we should interpret these with caution given the lack of statistical significance at the α = 0.05 level.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate estimated marginal means\nemm <- emmeans(nested_model, ~ treat)\n\nsummary(emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n treat   emmean   SE df lower.CL upper.CL\n control    1.3 9.41 12   -19.20     21.8\n dens_33   21.6 9.41 12     1.05     42.0\n dens_66   19.0 9.41 12    -1.50     39.5\n removal   39.2 9.41 12    18.70     59.7\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: Tukey Pairwise Comparisons\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pairwise comparisons with Tukey adjustment\npairs <- pairs(emm, adjust = \"tukey\")\npairs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE df t.ratio p.value\n control - dens_33   -20.25 13.3 12  -1.522  0.4553\n control - dens_66   -17.70 13.3 12  -1.330  0.5625\n control - removal   -37.90 13.3 12  -2.849  0.0615\n dens_33 - dens_66     2.55 13.3 12   0.192  0.9974\n dens_33 - removal   -17.65 13.3 12  -1.327  0.5646\n dens_66 - removal   -20.20 13.3 12  -1.518  0.4573\n\nDegrees-of-freedom method: kenward-roger \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: Letter Display\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract compact letter display for plotting\ncld <- multcomp::cld(emm, alpha = 0.05, Letters = letters)\n\ncld\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n treat   emmean   SE df lower.CL upper.CL .group\n control    1.3 9.41 12   -19.20     21.8  a    \n dens_66   19.0 9.41 12    -1.50     39.5  a    \n dens_33   21.6 9.41 12     1.05     42.0  a    \n removal   39.2 9.41 12    18.70     59.7  a    \n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 4 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n::: {.callout-important appearance=\"simple\"}\nInterpretation of Treatment Comparisons The mean algae cover for the Control treatment (1.30%) appears considerably lower than for the reduced urchin density treatments (66% Density: 21.55%, 33% Density: 19.00%, Removed: 39.20%). While the visual pattern suggests an inverse relationship between urchin density and algae cover, with complete removal showing the highest algae cover, the nested ANOVA showed that these differences were not statistically significant at the α = 0.05 level (p = xxxx). The high variability among patches within treatments likely contributed to the lack of statistical significance for the treatment effect.\n:::\n\n# Lecture 13: ANOVA Assumptions Testing\n\nFor valid inference from ANOVA, several assumptions must be met. We test these assumptions below.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract residuals\nresiduals <- residuals(nested_model)\n\n# QQ plot\nqq_plot <- ggplot(data.frame(residuals = residuals), aes(sample = residuals)) +\n  stat_qq() +\n  stat_qq_line() +\n  # theme_cowplot() +\n  labs(title = \"Normal Q-Q Plot of Residuals\",\n       x = \"Theoretical Quantiles\",\n       y = \"Sample Quantiles\")\n\n# Histogram of residuals\nhist_plot <- ggplot(data.frame(residuals = residuals), aes(x = residuals)) +\n  geom_histogram(bins = 15, fill = \"lightblue\", color = \"black\") +\n  # theme_cowplot() +\n  labs(title = \"Histogram of Residuals\",\n       x = \"Residuals\",\n       y = \"Frequency\")\n\n# Residuals vs. Fitted plot\nfitted_values <- fitted(nested_model)\nresid_plot <- ggplot(data.frame(fitted = fitted_values, residuals = residuals), \n                    aes(x = fitted, y = residuals)) +\n  geom_point() +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  # theme_cowplot() +\n  labs(title = \"Residuals vs. Fitted Values\",\n       x = \"Fitted Values\",\n       y = \"Residuals\")\n\n# Combine plots\nqq_plot + hist_plot + resid_plot + plot_layout(ncol = 3)\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/unnamed-chunk-5-1.png){width=336}\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: Levenes Test for Homogeneity of Variance\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Homogeneity of Variance\n# Levene's test\n# Levene's test for homogeneity of variance\nlevene_test <- leveneTest(algae ~ treat, data = urchin_df)\nlevene_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value     Pr(>F)    \ngroup  3  8.1694 0.00008785 ***\n      76                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n::: {.callout-important appearance=\"simple\"}\nInterpretation of Assumption Tests The Q-Q plot shows some deviation from normality, particularly in the tails, and Levene's test indicates significant heterogeneity of variances across treatments (F = (xxxxx). As noted by Quinn & Keough (2002), there were \"large differences in within-cell variances\" in this dataset, and transformations (including arcsin) did not improve variance homogeneity. However, ANOVA is generally robust to heteroscedasticity with balanced designs, which is why they chose to analyze untransformed data. The residuals vs. fitted plot also shows a pattern of increasing variance with increasing fitted values, confirming the heteroscedasticity.\n:::\n\n# Lecture 13: Visualization\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplot\nggplot_boxplot <- ggplot(urchin_df, aes(x = treat, y = algae, fill = treat)) +\n  geom_boxplot(alpha = 0.7, outlier.shape = NA) +\n  geom_jitter(width = 0.2, alpha = 0.4, size = 1) +\n  scale_fill_viridis_d(option = \"D\", end = 0.85) +\n  labs(\n    title = \"Effect of Urchin Density on Filamentous Algae Cover\",\n    x = \"Urchin Density Treatment\",\n    y = \"Filamentous Algae Cover (%)\",\n    caption = \"Figure 1: Boxplots showing the distribution of algal cover across urchin density treatments.\\nDespite visual differences, the treatment effect was not statistically significant (p = 0.091).\"\n  ) +\n  # theme_cowplot() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\", size = 12),\n    axis.text = element_text(size = 10),\n    plot.caption = element_text(hjust = 0, face = \"italic\", size = 10)\n  )\n\nprint(ggplot_boxplot)\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/unnamed-chunk-7-1.png){width=336}\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: Means Plot\n\n-   text\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create means plot\nmeans_plot <- ggplot(summary_stats, aes(x = treat, y = mean, group = 1)) +\n  # geom_line(size = 1) +\n  geom_point(size = 3, shape = 21, fill = \"white\") +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +\n  labs(\n    title = \"Mean Algae Cover by Urchin Density Treatment\",\n    x = \"Urchin Density Treatment\",\n    y = \"Mean Filamentous Algae Cover (%)\",\n    caption = \"Figure 2: Mean (± SE) percentage cover of filamentous algae across urchin density treatments.\"\n  ) +\n  # theme_cowplot() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\", size = 12),\n    axis.text = element_text(size = 10),\n    plot.caption = element_text(hjust = 0, face = \"italic\", size = 10)\n  )\n\nprint(means_plot)\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/unnamed-chunk-8-1.png){width=336}\n:::\n:::\n\n\n\n\n\n\n\n\n# Lecture 13: Discussion\n\n::: {.callout-important appearance=\"simple\"}\nScientific Interpretation Our nested ANOVA analysis revealed substantial spatial heterogeneity in algae cover, with significant variation among patches within each treatment (p \\< 0.001). Surprisingly, the effect of urchin density treatments on filamentous algae cover was not statistically significant at the α = 0.05 level (p = 0.091), despite apparent trends in the data. The descriptive statistics show a pattern where algae cover appears to increase as urchin density decreases, with the Control treatment (mean = 1.3%) showing minimal algae cover compared to reduced density treatments (66% Density: 21.55%, 33% Density: 19.00%, and Removed: 39.20%). This pattern suggests a potential density-dependent relationship between urchin grazing and algal abundance, but the high variability among patches masked the treatment effect. The substantial variance component associated with patches nested within treatments (294.31, approximately 39.5% of total variance) underscores the importance of spatial heterogeneity in structuring algal communities. This finding highlights the necessity of accounting for spatial variability when designing and analyzing ecological field experiments. From an ecological perspective, these results suggest that while sea urchins may influence algal communities through grazing, local environmental factors and patch-specific conditions play a dominant role in determining algae cover. This has important implications for ecosystem management, as it indicates that the effects of urchin density manipulations may be context-dependent and influenced by local environmental conditions.\n:::\n\n# THE ALTERNATE WAY AND BETTER!!!\n\n# Mixed Model Analysis\n\nIn this experimental design, patch is nested within treat because each patch received only one treatment level. This hierarchical design is well-suited for analysis using linear mixed-effects models.\n\n## Model Specification\n\nWe'll use the following model specification:\n\n$algae_{ijk} = \\mu + \\alpha_i + \\beta_{j(i)} + \\epsilon_{ijk}$\n\nWhere: - $\\mu$ is the overall mean - $\\alpha_i$ is the fixed effect of treatment $i$ - $\\beta_{j(i)}$ is the random effect of patch $j$ nested within treatment $i$ - $\\epsilon_{ijk}$ is the residual error for quadrat $k$ in patch $j$ within treatment $i$\n\nIn `lme4`, this model is specified as\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the mixed model\nmixed_model <- lmer(algae ~ treat + (1|treat:patch), data = urchin_df)\n\n# Display model summary\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: algae ~ treat + (1 | treat:patch)\n   Data: urchin_df\n\nREML criterion at convergence: 682.2\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.9808 -0.3106 -0.1093  0.2831  2.5910 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n treat:patch (Intercept) 294.3    17.16   \n Residual                298.6    17.28   \nNumber of obs: 80, groups:  treat:patch, 16\n\nFixed effects:\n             Estimate Std. Error     df t value Pr(>|t|)  \n(Intercept)     1.300      9.408 12.000   0.138   0.8924  \ntreatdens_33   20.250     13.305 12.000   1.522   0.1539  \ntreatdens_66   17.700     13.305 12.000   1.330   0.2081  \ntreatremoval   37.900     13.305 12.000   2.849   0.0147 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) trt_33 trt_66\ntreatdns_33 -0.707              \ntreatdns_66 -0.707  0.500       \ntreatremovl -0.707  0.500  0.500\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## ANOVA Table\n\nThe ANOVA table for the mixed model:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get ANOVA table with Type III tests\nanova_table <- anova(mixed_model, type = 3)\nprint(anova_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n      Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \ntreat   2434  811.33     3    12  2.7171 0.09126 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Assumption Testing\n\nFor valid inference from mixed models, several assumptions must be met. We test these assumptions below.\n\n## Normality of Residuals\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# QQ plot of residuals\nqqnorm(resid(mixed_model))\nqqline(resid(mixed_model))\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/normality-1.png){width=336}\n:::\n\n```{.r .cell-code}\n# Histogram of residuals\nhist(resid(mixed_model), main = \"Histogram of Residuals\",\n     xlab = \"Residuals\", breaks = 15)\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/normality-2.png){width=336}\n:::\n\n```{.r .cell-code}\n# More advanced residual diagnostics using DHARMa\nsim_residuals <- simulateResiduals(fittedModel = mixed_model)\nplot(sim_residuals)\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/normality-3.png){width=336}\n:::\n:::\n\n\n\n\n\n\n\n\n## Homogeneity of Variance\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residuals vs. fitted values plot\nplot(fitted(mixed_model), resid(mixed_model),\n     xlab = \"Fitted Values\", ylab = \"Residuals\",\n     main = \"Residuals vs. Fitted Values\")\nabline(h = 0, lty = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/homogeneity-1.png){width=336}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Levene's test for homogeneity of variance\nlevene_test <- leveneTest(algae ~ treat, data = urchin_df)\nlevene_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value     Pr(>F)    \ngroup  3  8.1694 0.00008785 ***\n      76                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Post-hoc Comparisons\n\nAlthough the main effect of treatment was not significant in the nested ANOVA (p = xxxxx), we can still examine the mean differences between treatments to understand patterns in the data.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate estimated marginal means\nemm <- emmeans(mixed_model, ~ treat)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n treat   emmean   SE df lower.CL upper.CL\n control    1.3 9.41 12   -19.20     21.8\n dens_33   21.6 9.41 12     1.05     42.0\n dens_66   19.0 9.41 12    -1.50     39.5\n removal   39.2 9.41 12    18.70     59.7\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pairwise comparisons with Tukey adjustment\npairs <- pairs(emm, adjust = \"tukey\")\npairs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE df t.ratio p.value\n control - dens_33   -20.25 13.3 12  -1.522  0.4553\n control - dens_66   -17.70 13.3 12  -1.330  0.5625\n control - removal   -37.90 13.3 12  -2.849  0.0615\n dens_33 - dens_66     2.55 13.3 12   0.192  0.9974\n dens_33 - removal   -17.65 13.3 12  -1.327  0.5646\n dens_66 - removal   -20.20 13.3 12  -1.518  0.4573\n\nDegrees-of-freedom method: kenward-roger \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compact letter display\ncld <- multcomp::cld(emm, alpha = 0.05, Letters = letters)\ncld\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n treat   emmean   SE df lower.CL upper.CL .group\n control    1.3 9.41 12   -19.20     21.8  a    \n dens_66   19.0 9.41 12    -1.50     39.5  a    \n dens_33   21.6 9.41 12     1.05     42.0  a    \n removal   39.2 9.41 12    18.70     59.7  a    \n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 4 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n# Visualization\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplot with jittered points\nggplot_boxplot <- ggplot(urchin_df, aes(x = treat, y = algae, fill = treat)) +\n  geom_boxplot(alpha = 0.7, outlier.shape = NA) +\n  geom_jitter(width = 0.2, alpha = 0.4, size = 1) +\n  scale_fill_viridis_d(option = \"D\", end = 0.85) +\n  labs(\n    title = \"Urchin Density effect on Algae Cover\",\n    x = \"Urchin Density \",\n    y = \"Algae Cover (%)\",\n    caption = \"Figure 1: Boxplots showing the distribution of algal cover across urchin density.\\nDespite visual differences, the treatment effect was not statistically significant (p = 0.091).\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\", size = 12),\n    axis.text = element_text(size = 10),\n    plot.caption = element_text(hjust = 0, face = \"italic\", size = 10)\n  )\n\n# Create means plot with error bars\nmeans_plot <- ggplot(summary_stats, aes(x = treat, y = mean, group = 1)) +\n  geom_point(size = 3, shape = 21, fill = \"white\") +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +\n  labs(\n    title = \"Mean Algae Cover by Urchin Density\",\n    x = \"Urchin Density\",\n    y = \"Algae Cover (%)\",\n    caption = \"Figure 2: Mean (± SE) percentage cover of algae across urchin density treatments.\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\", size = 12),\n    axis.text = element_text(size = 10),\n    plot.caption = element_text(hjust = 0, face = \"italic\", size = 10)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display plots\nggplot_boxplot\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/unnamed-chunk-12-1.png){width=336}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmeans_plot\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/unnamed-chunk-13-1.png){width=336}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combined plot using patchwork\nggplot_boxplot + means_plot + plot_layout(ncol = 1)\n```\n\n::: {.cell-output-display}\n![](13_02_class_activity_files/figure-html/unnamed-chunk-14-1.png){width=576}\n:::\n:::\n\n\n\n\n\n\n\n\n# Comparison with Traditional Nested ANOVA\n\nThe linear mixed model approach provides similar results to the traditional nested ANOVA approach. The main advantage of the mixed model is the more elegant handling of random effects and the extensive diagnostic tools available through packages like DHARMa.\n\nThe mixed model approach confirms that:\n\n1.  Treatment effects are not significant (p = 0.091)\n2.  Patches within treatments show significant variation (p \\< 0.001)\n3.  The variance components are similar to those from the traditional approach\n\nIn both methods, the key ecological finding is the strong spatial heterogeneity in algal cover that overrides the grazing effect of urchins at different densities.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}